import {boundedText} from '@/lib/commerce/http';
import {NextRequest} from 'next/server';
import {requestIsOwner} from '@/lib/owner-auth';
import {sameOrigin} from '@/lib/owner-api';
import {CommerceStore} from '@/lib/commerce/store';
import {prepareCatalog,approveCatalog,eligibleReleases} from '@/lib/commerce/catalog';
import {reconcileOrder} from '@/lib/commerce/reconcile';
import {commerceConfig} from '@/lib/commerce/config';
import {z} from 'zod';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function GET(r:NextRequest){if(!await requestIsOwner(r))return Response.json({message:'Sign in required.'},{status:401});const s=new CommerceStore();try{return Response.json({...s.overview(),eligibleReleases:eligibleReleases(),configuration:commerceConfig()},{headers:{'Cache-Control':'no-store'}});}finally{s.close();}}
const commands=z.discriminatedUnion('action',[z.object({action:z.literal('prepare'),projectId:z.uuid(),websiteStock:z.number().int().min(0).max(10000),photoUrl:z.url().max(1000).refine(s=>{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password;})}).strict(),z.object({action:z.literal('approve'),id:z.uuid()}).strict(),z.object({action:z.literal('withdraw'),id:z.uuid()}).strict(),z.object({action:z.literal('inventory'),id:z.uuid(),stock:z.number().int().min(0).max(10000)}).strict(),z.object({action:z.literal('fulfill'),id:z.uuid(),note:z.string().trim().min(1).max(1000)}).strict(),z.object({action:z.literal('reissue'),id:z.uuid()}).strict(),z.object({action:z.literal('revoke'),id:z.uuid()}).strict(),z.object({action:z.literal('reconcile'),id:z.uuid()}).strict(),z.object({action:z.literal('cancelUnknown'),id:z.uuid(),confirmedNoStripePayment:z.literal(true),note:z.string().trim().min(10).max(1000)}).strict()]);
export async function POST(r:NextRequest){if(!sameOrigin(r))return Response.json({message:'Origin rejected.'},{status:403});if(!await requestIsOwner(r))return Response.json({message:'Sign in required.'},{status:401});let s:CommerceStore|undefined;try{const text=await boundedText(r,4000);if(text.length>4000)throw Error();const v=commands.parse(JSON.parse(text));s=new CommerceStore();if(v.action==='prepare')prepareCatalog(s,v.projectId,v.photoUrl,v.websiteStock);else if(v.action==='approve')approveCatalog(s,v.id);else if(v.action==='withdraw')s.withdraw(v.id);else if(v.action==='inventory')s.inventory(v.id,v.stock);else if(v.action==='reissue')return Response.json({token:s.reissue(v.id)},{headers:{'Cache-Control':'no-store'}});else if(v.action==='revoke')s.revoke(v.id);else if(v.action==='reconcile')await reconcileOrder(s,v.id);else if(v.action==='cancelUnknown')s.cancelUnknown(v.id,v.note);else s.fulfill(v.id,v.note);return Response.json({message:'Saved.'});}catch{return Response.json({message:'Action rejected. Check current tested revision, approval or reserved stock.'},{status:409});}finally{s?.close();}}
