import 'server-only';
import {z} from 'zod';
import type {MarketplaceStore,EtsyToken} from './store.ts';
import type {ProductProject} from '../ai-center/projects.ts';
import type {Job} from '../ai-center/types.ts';

const SCOPES=['shops_r','listings_r','transactions_r'];
const API='https://api.etsy.com/v3/application';
const TOKEN='https://api.etsy.com/v3/public/oauth/token';
const id=z.number().int().positive().safe();
const shortText=z.string().max(500);
const money=z.object({amount:z.number().int().nonnegative().max(1_000_000_000),divisor:z.number().int().positive().max(1_000_000),currency_code:z.string().regex(/^[A-Z]{3}$/)});
const tokenReply=z.object({access_token:z.string().regex(/^\d+\.[A-Za-z0-9_-]+$/).max(4096),refresh_token:z.string().regex(/^\d+\.[A-Za-z0-9_-]+$/).max(4096),token_type:z.literal('Bearer'),expires_in:z.number().int().min(60).max(86400),scope:z.string().max(500).optional()});
const shopReply=z.object({shop_id:id,user_id:id,shop_name:z.string().min(1).max(100)});
const transaction=z.object({transaction_id:id,listing_id:id,title:shortText,quantity:z.number().int().positive().max(10000),price:money});
const receipt=z.object({receipt_id:id,is_paid:z.boolean(),status:z.string().max(100),transactions:z.array(transaction).max(100),refunds:z.array(z.unknown()).max(100).optional()});
const receiptsReply=z.object({count:z.number().int().nonnegative().safe(),results:z.array(receipt).max(100)});
const listing=z.object({listing_id:id,title:shortText,num_favorers:z.number().int().nonnegative().safe().optional(),price:money});
const listingsReply=z.object({count:z.number().int().nonnegative().safe(),results:z.array(listing).max(25)});
export {access as authorizedEtsyToken};
export async function etsyListingRequest(endpoint:string,options:RequestInit,accessToken:string,fetcher:typeof fetch=fetch){
 if(!/^\/shops\/\d+(?:\/listings(?:\/\d+(?:\/(?:images|files))?)?)?$/.test(endpoint))throw Error('Invalid Etsy listing endpoint.');
 const c=config();return request(API+endpoint,{...options,headers:{'x-api-key':`${c.key}:${c.secret}`,Authorization:`Bearer ${accessToken}`,...options.headers}},fetcher);
}
export const salesRequestSchema=z.object({days:z.number().int().min(1).max(365),maxPages:z.number().int().min(1).max(3)}).strict();

export function connectionConfiguration(){const missing=['ETSY_APP_KEY','ETSY_SHARED_SECRET','ETSY_REDIRECT_URI','MARKETPLACE_TOKEN_KEY'].filter(k=>!process.env[k]);if(process.env.MARKETPLACE_TOKEN_KEY&&!/^[a-fA-F0-9]{64}$/.test(process.env.MARKETPLACE_TOKEN_KEY))missing.push('MARKETPLACE_TOKEN_KEY (32-byte hexadecimal)');const enabled=process.env.ETSY_ENABLED==='true';return {enabled,writesEnabled:process.env.ETSY_WRITES_ENABLED==='true',missing,expectedShop:process.env.ETSY_EXPECTED_SHOP_NAME||'MeshHarbor3D',mode:process.env.ETSY_WRITES_ENABLED==='true'?'Owner-approved single-listing publication enabled':'Read-only OAuth; publication disabled'};}
function config(){const status=connectionConfiguration();if(!status.enabled||status.missing.length)throw Error('Etsy is disabled or requires server configuration.');const key=process.env.ETSY_APP_KEY!,secret=process.env.ETSY_SHARED_SECRET!,redirect=process.env.ETSY_REDIRECT_URI!;if(!/^[A-Za-z0-9_-]{1,200}$/.test(key)||!/^[A-Za-z0-9_-]{1,200}$/.test(secret))throw Error('Invalid Etsy application configuration.');const url=new URL(redirect);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash||url.pathname!=='/api/owner/marketplace/callback'||url.origin!==new URL(process.env.NEXT_PUBLIC_SITE_URL||redirect).origin)throw Error('Register the exact HTTPS same-site Etsy callback URL.');return {key,secret,redirect,expectedShop:status.expectedShop};}
async function boundedJson(response:Response){if(!response.ok)throw Error(response.status===429?'Etsy rate limit reached. Wait before requesting again.':'Etsy request failed. Check app access, scopes and authorization.');if(Number(response.headers.get('content-length')||0)>2_000_000)throw Error('Etsy response exceeds the safety limit.');const reader=response.body?.getReader();if(!reader)throw Error('Invalid Etsy response.');let size=0;const chunks:Uint8Array[]=[];try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>2_000_000){await reader.cancel();throw Error('Etsy response exceeds the safety limit.');}chunks.push(value);}return JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;}catch{throw Error('Invalid or oversized Etsy response.');}finally{reader.releaseLock();}}
async function request(url:string,options:RequestInit,fetcher:typeof fetch){try{return await boundedJson(await fetcher(url,{...options,cache:'no-store',redirect:'error',signal:AbortSignal.timeout(12_000)}));}catch(e){if(e instanceof Error&&/^Etsy |^Invalid or oversized/.test(e.message))throw e;throw Error('Etsy request failed or timed out. No automatic retry.');}}
async function get(endpoint:string,token:string|undefined,fetcher:typeof fetch){const c=config();return request(API+endpoint,{method:'GET',headers:{'x-api-key':`${c.key}:${c.secret}`,...(token?{Authorization:`Bearer ${token}`}:{})}},fetcher);}
async function exchange(body:Record<string,string>,fetcher:typeof fetch){const c=config();const value=await request(TOKEN,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','x-api-key':`${c.key}:${c.secret}`},body:new URLSearchParams({...body,client_id:c.key}).toString()},fetcher);const parsed=tokenReply.safeParse(value);if(!parsed.success)throw Error('Invalid Etsy authorization response.');return parsed.data;}
export function beginAuthorization(store:MarketplaceStore,ownerSession:string,now=Date.now(),writes=false){if(writes&&process.env.ETSY_WRITES_ENABLED!=='true')throw Error('Etsy writes are disabled.');const c=config(),pkce=store.challenge(ownerSession,now,writes),url=new URL('https://www.etsy.com/oauth/connect');url.search=new URLSearchParams({response_type:'code',client_id:c.key,redirect_uri:c.redirect,scope:[...SCOPES,...(writes?['listings_w']:[])].join(' '),state:pkce.state,code_challenge:pkce.challenge,code_challenge_method:'S256'}).toString();return {url:url.toString(),expiresInSeconds:600};}
export async function completeAuthorization(store:MarketplaceStore,ownerSession:string,state:string,code:string,fetcher:typeof fetch=fetch,now=Date.now()){
 if(!/^[A-Za-z0-9_-]{43}$/.test(state)||!code||code.length>2048)throw Error('Authorization parameters invalid.');const c=config(),epoch=store.epoch(),challenge=store.consume(ownerSession,state,now),lease=store.lease('authorization',now,60_000,0);
 try{if(challenge.writes&&process.env.ETSY_WRITES_ENABLED!=='true')throw Error('Etsy writes are disabled.');const expected=[...SCOPES,...(challenge.writes?['listings_w']:[])];const token=await exchange({grant_type:'authorization_code',redirect_uri:c.redirect,code,code_verifier:challenge.verifier},fetcher);const scopes=(token.scope||'').split(' ').filter(Boolean);if(!expected.every(s=>scopes.includes(s))||scopes.some(s=>!expected.includes(s)))throw Error('Etsy authorization must grant exactly the requested scopes.');const userId=Number(token.access_token.split('.')[0]);if(!Number.isSafeInteger(userId)||userId<=0)throw Error('Invalid Etsy authorization response.');const parsed=shopReply.safeParse(await get(`/users/${userId}/shops`,token.access_token,fetcher));if(!parsed.success||parsed.data.user_id!==userId||parsed.data.shop_name.toLowerCase()!==c.expectedShop.toLowerCase())throw Error('Authorized Etsy shop does not match the configured owner shop.');store.saveToken({accessToken:token.access_token,refreshToken:token.refresh_token,expiresAt:now+token.expires_in*1000,scopes,shopId:parsed.data.shop_id,userId,shopName:parsed.data.shop_name},epoch);return store.status(now);}finally{store.release('authorization',lease);}
}
async function access(store:MarketplaceStore,fetcher:typeof fetch,now:number):Promise<EtsyToken>{let token=store.token();if(!token)throw Error('Authorize the owner Etsy shop first.');if(token.shopName.toLowerCase()!==config().expectedShop.toLowerCase())throw Error('Authorized Etsy shop does not match the configured owner shop.');if(token.expiresAt>now+30_000)return token;const lease=store.lease('authorization',now,60_000,0);try{const epoch=store.epoch();token=store.token();if(!token)throw Error('Authorize the owner Etsy shop first.');if(token.expiresAt>now+30_000)return token;const refreshed=await exchange({grant_type:'refresh_token',refresh_token:token.refreshToken},fetcher);if(Number(refreshed.access_token.split('.')[0])!==token.userId)throw Error('Invalid Etsy refresh identity.');const scopes=refreshed.scope?refreshed.scope.split(' ').filter(Boolean):token.scopes;const expected=token.scopes;if(!expected.every(s=>scopes.includes(s))||scopes.some(s=>!expected.includes(s)))throw Error('Invalid Etsy refresh scopes.');token={...token,accessToken:refreshed.access_token,refreshToken:refreshed.refresh_token,expiresAt:now+refreshed.expires_in*1000,scopes};store.saveToken(token,epoch);return token;}finally{store.release('authorization',lease);}}
export async function observeMarket(store:MarketplaceStore,keywords:string,fetcher:typeof fetch=fetch,now=Date.now()){
 const query=z.string().trim().min(1).max(120).parse(keywords);config();const lease=store.lease('reads',now);
 try{const parameters=new URLSearchParams({keywords:query,limit:'25',offset:'0',sort_on:'score'}),source=API+'/listings/active?'+parameters;const parsed=listingsReply.safeParse(await get('/listings/active?'+parameters,undefined,fetcher));if(!parsed.success)throw Error('Invalid Etsy market payload.');const result={kind:'market' as const,query,source,observedAt:new Date(now).toISOString(),reportedMatches:parsed.data.count,items:parsed.data.results.map(l=>({id:l.listing_id,title:l.title,url:`https://www.etsy.com/listing/${l.listing_id}`,favorites:l.num_favorers??null,priceCents:Math.round(l.price.amount*100/l.price.divisor),currency:l.price.currency_code})),limitations:'First 25 official keyword-search observations only. Search score and favorites are proxies, not competitor item sales, demand validation, or bestseller rankings. No reviews, sales counts or scraped estimates are invented. Listing text is untrusted source material; inspect originality before using ideas.'};store.record(result,now);return result;}finally{store.release('reads',lease);}
}
export async function readOwnSales(store:MarketplaceStore,input:z.infer<typeof salesRequestSchema>,fetcher:typeof fetch=fetch,now=Date.now()){
 const {days,maxPages}=salesRequestSchema.parse(input);config();const lease=store.lease('reads',now);
 try{const token=await access(store,fetcher,now),from=Math.max(946684800,Math.floor((now-days*86400000)/1000)),to=Math.max(from,Math.floor(now/1000));const seenReceipts=new Set<number>(),seenTransactions=new Set<number>(),groups=new Map<string,{listingId:number;title:string;currency:string;units:number;itemGrossCents:number;url:string}>();let pages=0,total=0,truncated=false,refundReceipts=0;const sources:string[]=[];
  for(let page=0;page<maxPages;page++){const parameters=new URLSearchParams({limit:'100',offset:String(page*100),was_paid:'true',was_canceled:'false',min_created:String(from),max_created:String(to)});const endpoint=`/shops/${token.shopId}/receipts?${parameters}`;sources.push(API+endpoint);const parsed=receiptsReply.safeParse(await get(endpoint,token.accessToken,fetcher));if(!parsed.success)throw Error('Invalid Etsy receipt payload.');pages++;total=parsed.data.count;
   for(const r of parsed.data.results){if(seenReceipts.has(r.receipt_id))continue;seenReceipts.add(r.receipt_id);if(!r.is_paid||r.status==='canceled')continue;if(r.refunds?.length)refundReceipts++;for(const t of r.transactions){if(seenTransactions.has(t.transaction_id))continue;seenTransactions.add(t.transaction_id);const groupKey=`${t.listing_id}:${t.price.currency_code}`,g=groups.get(groupKey)||{listingId:t.listing_id,title:t.title,currency:t.price.currency_code,units:0,itemGrossCents:0,url:`https://www.etsy.com/listing/${t.listing_id}`};g.units+=t.quantity;g.itemGrossCents+=Math.round(t.price.amount*100/t.price.divisor)*t.quantity;if(!Number.isSafeInteger(g.itemGrossCents)||!Number.isSafeInteger(g.units))throw Error('Invalid Etsy transaction amounts.');groups.set(groupKey,g);}}
   truncated=(page+1)*100<total;if(parsed.data.results.length<100||!truncated){truncated=seenReceipts.size<total;break;}
  }
  const result={kind:'sales' as const,shopName:token.shopName,shopId:token.shopId,observedAt:new Date(now).toISOString(),windowDays:days,from:new Date(from*1000).toISOString(),to:new Date(to*1000).toISOString(),pages,receiptCount:seenReceipts.size,reportedReceiptCount:total,truncated,receiptsWithRefunds:refundReceipts,sources,rankings:[...groups.values()].sort((a,b)=>b.units-a.units),limitations:'Own authorized shop only: recorded transaction quantities in paid, non-canceled receipts, ranked by units in the requested window. Item gross excludes shipping/tax/fees and does not deduct refunds; it is not net revenue or profit. Capped at three pages (300 receipts); truncation means these are sample rankings. Different currencies are separate. No buyer contact details are retained.'};store.record(result,now);return result;
 }finally{store.release('reads',lease);}
}
export function exportListing(project:ProductProject,jobs:Job[],format:'physical'|'digital'){
 const revision=project.revisions.at(-1),release=project.release;if(!release||project.stage!=='release')throw Error('Prepare a release package first.');if(!revision||release.revisionId!==revision.id||!revision.tests.at(-1)?.passed)throw Error('Current revision must be physically tested.');const approved=jobs.find(j=>j.projectId===project.id&&j.key===`project-${project.id}-${project.version}-listing`&&j.kind==='listing'&&j.status==='ready');if(!approved)throw Error('A listing draft for this project version must be approved by the owner first.');return {platform:'Etsy',action:'manual-export-only',projectId:project.id,projectVersion:project.version,revisionId:revision.id,sha256:revision.sha256,format,title:project.name,description:release.description,reviewedDraft:approved.output,priceCents:format==='physical'?release.physicalPriceCents:release.digitalPriceCents,currency:'USD',suggestedStock:format==='physical'?release.stock:null,quantity:null,inventoryStatus:'Not allocated. Assign separate Etsy stock before publishing; no cross-channel stock synchronization exists.',license:release.license,asset:format==='digital'?revision.filename:null,checklist:['Confirm ownership and marketplace Creativity Standards','Supply accurate photos of tested item or digital contents','Allocate separate Etsy physical stock; never duplicate storefront availability','Confirm taxonomy, production partner, processing and return/shipping profiles','Review current Etsy fees and taxes before manual publication'],published:false};
}
