import 'server-only';
import {DatabaseSync} from 'node:sqlite';
import {createHash,randomUUID} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {z} from 'zod';
import {marketplaceDatabasePath} from './store.ts';
import type {MarketplaceStore} from './store.ts';
import {authorizedEtsyToken,etsyListingRequest,exportListing} from './etsy.ts';
import type {ProductProject} from '../ai-center/projects.ts';
import type {Job} from '../ai-center/types.ts';

const numberId=z.number().int().positive().safe();
export const publicationSchema=z.object({format:z.enum(['physical','digital']),title:z.string().trim().min(5).max(140),description:z.string().trim().min(20).max(10000),priceCents:z.number().int().min(50).max(1_000_000),allocatedQuantity:z.literal(1),taxonomyId:numberId,shippingProfileId:numberId.nullable(),readinessStateId:numberId.nullable(),returnPolicyId:numberId.nullable(),whenMade:z.enum(['2020_2026','made_to_order']),originalPhoto:z.literal(true),stockAllocated:z.literal(true),rightsReviewed:z.literal(true),policiesReviewed:z.literal(true)}).strict().superRefine((v,ctx)=>{if(v.format==='physical'&&(!v.shippingProfileId||!v.readinessStateId||!v.returnPolicyId))ctx.addIssue({code:'custom',message:'Physical products need existing shipping, processing and return-policy IDs.'});if(v.format==='digital'&&(v.shippingProfileId||v.readinessStateId||v.returnPolicyId))ctx.addIssue({code:'custom',message:'Digital products must omit physical profiles.'});});
type Input=z.infer<typeof publicationSchema>;
export type Publication={id:string;key:string;hash:string;projectId:string;version:number;shopId:number;ownerEpoch:number;createdAt:string;approvedAt:string|null;status:'preview'|'running'|'published'|'uncertain';listingId:number|null;step:string;package:{title:string;description:string;priceCents:number;quantity:1;format:Input['format'];taxonomyId:number;shippingProfileId:number|null;readinessStateId:number|null;returnPolicyId:number|null;whenMade:Input['whenMade'];shouldAutoRenew:false;photoFilename:string;photoSha256:string;revisionId:string;fileFilename:string;fileSha256:string;feePolicyUrl:string;expectedInitialFeeUsdCents:20;feeLimitations:string};};
const hash=(bytes:Buffer|string)=>createHash('sha256').update(bytes).digest('hex');
export class PublicationStore{
 private db:DatabaseSync;
 constructor(){const file=marketplaceDatabasePath();mkdirSync(path.dirname(file),{recursive:true});this.db=new DatabaseSync(file);this.db.exec('PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS marketplace_publications(id TEXT PRIMARY KEY,key TEXT UNIQUE NOT NULL,json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS marketplace_publication_assets(id TEXT PRIMARY KEY,photo BLOB NOT NULL,file BLOB NOT NULL);');}
 close(){this.db.close();}
 private tx<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.db.exec('COMMIT');return value;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 list(){return (this.db.prepare('SELECT json FROM marketplace_publications ORDER BY rowid DESC LIMIT 50').all() as {json:string}[]).map(r=>JSON.parse(r.json) as Publication);}
 get(id:string){const row=this.db.prepare('SELECT json FROM marketplace_publications WHERE id=?').get(id) as {json:string}|undefined;if(!row)throw Error('Publication preview not found.');return JSON.parse(row.json) as Publication;}
 private save(v:Publication){this.db.prepare('INSERT INTO marketplace_publications VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET json=excluded.json').run(v.id,v.key,JSON.stringify(v));return v;}
 preview(value:Publication,photo:Buffer,file:Buffer){return this.tx(()=>{const row=this.db.prepare('SELECT json FROM marketplace_publications WHERE key=?').get(value.key) as {json:string}|undefined;if(row){const old=JSON.parse(row.json) as Publication;if(old.hash===value.hash&&!(old.status==='preview'&&Date.now()-Date.parse(old.createdAt)>1800000))return old;if(old.status!=='preview')throw Error('Publication already attempted; reconcile the listing in Etsy before preparing another version.');value.id=old.id;}const usage=this.db.prepare('SELECT COALESCE(SUM(length(photo)+length(file)),0) AS bytes FROM marketplace_publication_assets').get() as {bytes:number};if(usage.bytes+photo.length+file.length>50_000_000)throw Error('Publication asset quota reached. Archive local packages with an approved maintenance process.');this.save(value);this.db.prepare('INSERT INTO marketplace_publication_assets VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET photo=excluded.photo,file=excluded.file').run(value.id,photo,file);return value;});}
 claim(id:string,expectedHash:string){return this.tx(()=>{const v=this.get(id);if(v.hash!==expectedHash)throw Error('Publication preview changed. Review it again.');if(v.status!=='preview')throw Error('Publication already attempted or pending reconciliation; no automatic retry.');if(Date.now()-Date.parse(v.createdAt)>1800000)throw Error('Publication preview expired. Prepare and review it again.');v.status='running';v.step='Owner approved exact preview, Etsy fee policy and publication';v.approvedAt=new Date().toISOString();return this.save(v);});}
 step(id:string,step:string,listingId?:number){return this.tx(()=>{const v=this.get(id);if(v.status!=='running')throw Error('Publication is not running.');v.step=step;if(listingId)v.listingId=listingId;return this.save(v);});}
 finish(id:string,status:'published'|'uncertain'){return this.tx(()=>{const v=this.get(id);v.status=status;v.step=status==='published'?'Etsy returned active; verify live listing before promoting':'Outcome uncertain. Check Etsy drafts/listings and fees manually. Never retry this package automatically.';return this.save(v);});}
 assets(id:string){const row=this.db.prepare('SELECT photo,file FROM marketplace_publication_assets WHERE id=?').get(id) as {photo:Uint8Array;file:Uint8Array}|undefined;if(!row)throw Error('Publication assets unavailable.');return {photo:Buffer.from(row.photo),file:Buffer.from(row.file)};}
}
function photoType(photo:Buffer,filename:string){if(photo.length<32||photo.length>8_000_000||!/^[a-zA-Z0-9._ -]{1,100}\.(png|jpe?g)$/i.test(filename))throw Error('Use an original JPEG or PNG photo under 8 MB.');if(/\.png$/i.test(filename)&&photo.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))&&photo.subarray(12,16).toString()==='IHDR'){const width=photo.readUInt32BE(16),height=photo.readUInt32BE(20);if(width>0&&height>0&&width<=12000&&height<=12000)return 'image/png';}if(/\.jpe?g$/i.test(filename)&&photo[0]===255&&photo[1]===216&&photo[2]===255&&photo.at(-2)===255&&photo.at(-1)===217)return 'image/jpeg';throw Error('Invalid original photo format. SVG and remote image URLs are not accepted.');}
export function preparePublication(pub:PublicationStore,store:MarketplaceStore,project:ProductProject,jobs:Job[],input:Input,photo:Buffer,filename:string,file:Buffer){
 const v=publicationSchema.parse(input),release=project.release;exportListing(project,jobs,v.format);if(!release?.original)throw Error('Original rights declaration required.');if(v.priceCents!==(v.format==='physical'?release.physicalPriceCents:release.digitalPriceCents))throw Error('Price changed; update and approve the project release first.');if(v.format==='physical'&&release.stock<1)throw Error('Allocate a separate physical Etsy unit first.');photoType(photo,filename);const token=store.token();if(!token||token.shopName.toLowerCase()!==(process.env.ETSY_EXPECTED_SHOP_NAME||'MeshHarbor3D').toLowerCase())throw Error('Authorize the configured Etsy shop first.');const revision=project.revisions.at(-1)!;if(file.length>20_000_000||hash(file)!==revision.sha256)throw Error('Publication must use the exact tested STL asset under 20 MB.');
 const pack:Publication['package']={title:v.title,description:v.description+'\n\n'+release.license,priceCents:v.priceCents,quantity:1,format:v.format,taxonomyId:v.taxonomyId,shippingProfileId:v.shippingProfileId,readinessStateId:v.readinessStateId,returnPolicyId:v.returnPolicyId,whenMade:v.whenMade,shouldAutoRenew:false,photoFilename:filename,photoSha256:hash(photo),revisionId:revision.id,fileFilename:revision.filename,fileSha256:revision.sha256,feePolicyUrl:'https://www.etsy.com/legal/fees/',expectedInitialFeeUsdCents:20,feeLimitations:'Etsy standard initial listing fee is USD $0.20. Taxes, currency conversion, sales transaction/payment/advertising fees or account fees may apply; actual Etsy billing is not capped by this application. Quantity is one and expiration auto-renew is disabled; no replenishment or renewal executor exists. Fees are separate from the $25 AI API ledger.'};
 const ownerEpoch=store.epoch(),contentHash=hash(JSON.stringify({pack,projectId:project.id,version:project.version,shopId:token.shopId,ownerEpoch}));return pub.preview({id:randomUUID(),key:`${project.id}:${project.version}:${v.format}`,hash:contentHash,projectId:project.id,version:project.version,shopId:token.shopId,ownerEpoch,createdAt:new Date().toISOString(),approvedAt:null,status:'preview',listingId:null,step:'Owner review required; no external request made',package:pack},photo,v.format==='digital'?file:Buffer.alloc(0));
}
export async function executePublication(pub:PublicationStore,store:MarketplaceStore,id:string,expectedHash:string,project:ProductProject,jobs:Job[],approval:{publish:boolean;fees:boolean;stock:boolean},fetcher:typeof fetch=fetch,validateCurrent:()=>void=()=>{}){
 if(process.env.ETSY_WRITES_ENABLED!=='true')throw Error('Etsy writes are disabled.');if(!approval.publish||!approval.fees||!approval.stock)throw Error('Explicit publication, fee and stock approval required.');const preview=pub.get(id);if(preview.hash!==expectedHash||preview.projectId!==project.id||preview.version!==project.version)throw Error('Publication or project changed. Review a new preview.');if(preview.status!=='preview')throw Error('Publication already attempted or pending reconciliation.');exportListing(project,jobs,preview.package.format);if(!project.release?.original)throw Error('Original rights declaration required.');if(preview.ownerEpoch!==store.epoch())throw Error('Authorization changed. Prepare a new preview.');const assets=pub.assets(id);if(hash(assets.photo)!==preview.package.photoSha256||(preview.package.format==='digital'&&hash(assets.file)!==preview.package.fileSha256))throw Error('Publication asset changed.');photoType(assets.photo,preview.package.photoFilename);
 const token=await authorizedEtsyToken(store,fetcher,Date.now());if(token.shopId!==preview.shopId||!token.scopes.includes('listings_w'))throw Error('Authorize listings_w for this exact shop first.');const shop=z.object({shop_id:numberId,user_id:numberId,shop_name:z.string(),currency_code:z.literal('USD')}).safeParse(await etsyListingRequest(`/shops/${token.shopId}`,{method:'GET'},token.accessToken,fetcher));if(!shop.success||shop.data.shop_id!==token.shopId||shop.data.user_id!==token.userId||shop.data.shop_name.toLowerCase()!==token.shopName.toLowerCase())throw Error('Verify a USD Etsy shop and ownership before publication.');
 // The claim commits before any external write. Recheck epoch and feature toggle
 // after read-only preflight; never retry any package after a write may have occurred.
 if(process.env.ETSY_WRITES_ENABLED!=='true'||preview.ownerEpoch!==store.epoch())throw Error('Authorization or write configuration changed.');validateCurrent();const intent=pub.claim(id,expectedHash),p=intent.package;
 try{const form=new URLSearchParams({quantity:'1',title:p.title,description:p.description,price:(p.priceCents/100).toFixed(2),who_made:'i_did',when_made:p.whenMade,taxonomy_id:String(p.taxonomyId),is_supply:'false',should_auto_renew:'false',type:p.format==='digital'?'download':'physical'});if(p.format==='physical'){form.set('shipping_profile_id',String(p.shippingProfileId));form.set('readiness_state_id',String(p.readinessStateId));form.set('return_policy_id',String(p.returnPolicyId));}
  const draft=z.object({listing_id:numberId,state:z.literal('draft')}).parse(await etsyListingRequest(`/shops/${token.shopId}/listings`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form.toString()},token.accessToken,fetcher));pub.step(id,'Draft created; image upload pending',draft.listing_id);
  const image=new FormData();image.set('image',new Blob([new Uint8Array(assets.photo)],{type:photoType(assets.photo,p.photoFilename)}),p.photoFilename);image.set('rank','1');z.object({listing_image_id:numberId}).parse(await etsyListingRequest(`/shops/${token.shopId}/listings/${draft.listing_id}/images`,{method:'POST',body:image},token.accessToken,fetcher));pub.step(id,'Image uploaded; asset/activation pending');
  if(p.format==='digital'){const digital=new FormData();digital.set('file',new Blob([new Uint8Array(assets.file)],{type:'application/octet-stream'}),p.fileFilename);digital.set('name',p.fileFilename);z.object({listing_file_id:numberId}).parse(await etsyListingRequest(`/shops/${token.shopId}/listings/${draft.listing_id}/files`,{method:'POST',body:digital},token.accessToken,fetcher));pub.step(id,'Tested digital file uploaded; activation pending');}
  if(process.env.ETSY_WRITES_ENABLED!=='true'||preview.ownerEpoch!==store.epoch())throw Error('Write configuration changed before activation.');validateCurrent();pub.step(id,'Activation requested; platform fees may be incurred');const active=z.object({listing_id:numberId,state:z.literal('active')}).parse(await etsyListingRequest(`/shops/${token.shopId}/listings/${draft.listing_id}`,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({state:'active',should_auto_renew:'false'}).toString()},token.accessToken,fetcher));if(active.listing_id!==draft.listing_id)throw Error('Unexpected listing identity.');return pub.finish(id,'published');
 }catch{return pub.finish(id,'uncertain');}
}
