import 'server-only';
import {randomBytes} from 'node:crypto';
import type Stripe from 'stripe';
import {stripeClient,assertStripeNewCommerceAllowed,stripeKeyMode} from '@/lib/stripe-client';
import {siteOrigin} from '@/lib/stripe-checkout';
import {CommerceStore,cartSchema} from './store.ts';
import {checkoutConfiguration} from './config.ts';
import {visibleCatalog} from './catalog.ts';
export async function startCheckout(input:unknown,email:string,customerId:string){const cart=cartSchema.parse(input),physical=cart.some(i=>!i.digital),config=checkoutConfiguration(physical);assertStripeNewCommerceAllowed();if(!process.env.COMMERCE_STRIPE_WEBHOOK_SECRET?.startsWith('whsec_'))throw Error('Signed payment webhook is required.');const origin=siteOrigin();if(process.env.NODE_ENV==='production'&&!origin.startsWith('https://'))throw Error('HTTPS site required.');const store=new CommerceStore();try{const visible=new Set(visibleCatalog(store).map(p=>p.id));if(cart.some(i=>!visible.has(i.id)))throw Error('Catalog changed.');const {order,token}=store.reserve(cart,physical?config.shippingCents:0,stripeKeyMode()==='live',customerId);const params:Stripe.Checkout.SessionCreateParams={mode:'payment',customer_email:email,integration_identifier:'meshharbor_catalog_'+randomBytes(8).toString('hex'),expires_at:Math.floor(Date.now()/1000)+1800,success_url:origin+'/cart?order='+order.id,cancel_url:origin+'/cart?order='+order.id,billing_address_collection:'required',automatic_tax:{enabled:config.automaticTax},line_items:order.items.map(i=>({quantity:i.quantity,price_data:{currency:'usd',unit_amount:i.priceCents,tax_behavior:'exclusive',product_data:{name:i.name+(i.digital?' — STL download':' — physical print')}}})),metadata:{commerce_order_id:order.id,commerce_fingerprint:order.fingerprint},payment_intent_data:{metadata:{commerce_order_id:order.id}}};if(physical){params.shipping_address_collection={allowed_countries:config.countries as Stripe.Checkout.SessionCreateParams.ShippingAddressCollection.AllowedCountry[]};params.shipping_options=[{shipping_rate_data:{display_name:'Configured standard shipping',type:'fixed_amount',fixed_amount:{amount:config.shippingCents,currency:'usd'}}}];}const session=await stripeClient().checkout.sessions.create(params,{idempotencyKey:'catalog-'+order.id});store.bind(order.id,session.id);if(!session.url)throw Error('Checkout URL unavailable.');return {url:session.url,orderId:order.id,token};}finally{store.close();}}
