import 'server-only';
import {DatabaseSync} from 'node:sqlite';
import {createHash,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {z} from 'zod';
export type Product={id:string;projectId:string;revisionId:string;name:string;description:string;license:string;physicalPriceCents:number;digitalPriceCents:number;costCents:number;stock:number;filename:string;sha256:string;photoUrl:string;status:'draft'|'approved'|'withdrawn';createdAt:string};
export const cartSchema=z.array(z.object({id:z.uuid(),digital:z.boolean(),quantity:z.number().int().min(1).max(20)}).strict()).min(1).max(20);
type Item=z.infer<typeof cartSchema>[number]&{name:string;revisionId:string;priceCents:number};
export type Order={id:string;status:'reserved'|'paid'|'expired'|'shipped'|'revoked';items:Item[];subtotalCents:number;shippingCents:number;taxCents:number;totalCents:number;fingerprint:string;sessionId:string;live:boolean;tokenHash:string;createdAt:string;shipping:unknown;paymentIntent:string;fulfillment:string;actor?:string;refundedCents?:number};
const hash=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
export function commercePath(){const business=path.resolve(/*turbopackIgnore: true*/ process.env.DATABASE_PATH||path.join(process.env.RAILWAY_VOLUME_MOUNT_PATH||path.join(process.cwd(),'data'),'3d-printing-business.sqlite'));const file=path.resolve(/*turbopackIgnore: true*/ process.env.COMMERCE_DATABASE_PATH||path.join(path.dirname(business),'commerce.sqlite'));const ai=path.resolve(/*turbopackIgnore: true*/ process.env.AI_CENTER_DATABASE_PATH||path.join(path.dirname(business),'ai-business-center.sqlite'));const marketplace=path.resolve(/*turbopackIgnore: true*/ process.env.MARKETPLACE_DATABASE_PATH||path.join(path.dirname(business),'marketplace.sqlite'));if([business,ai,marketplace].some(v=>v.toLowerCase()===file.toLowerCase()))throw Error('Commerce needs a separate database.');return file;}
const sessionSchema=z.object({id:z.string(),payment_status:z.string().optional(),amount_subtotal:z.number().int().optional(),amount_total:z.number().int().optional(),currency:z.string().optional(),livemode:z.boolean(),payment_intent:z.string().nullable().optional(),collected_information:z.object({shipping_details:z.unknown().optional()}).optional(),shipping_details:z.unknown().optional(),total_details:z.object({amount_shipping:z.number().int(),amount_tax:z.number().int().min(0),amount_discount:z.number().int()} ).optional(),metadata:z.object({commerce_order_id:z.uuid(),commerce_fingerprint:z.string()})});
export const commerceDatabasePath=commercePath;
export class CommerceStore {
 private db:DatabaseSync;
 constructor(file=commercePath()){mkdirSync(path.dirname(file),{recursive:true});this.db=new DatabaseSync(file);this.db.exec('PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS catalog(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, revision_id TEXT NOT NULL, json TEXT NOT NULL, data BLOB NOT NULL, UNIQUE(project_id,revision_id)); CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,json TEXT NOT NULL);');}
 close(){this.db.close();}
 private tx<T>(fn:()=>T){this.db.exec('BEGIN IMMEDIATE');try{const v=fn();this.db.exec('COMMIT');return v;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 private products(){return (this.db.prepare('SELECT json FROM catalog ORDER BY rowid DESC').all() as {json:string}[]).map(r=>JSON.parse(r.json) as Product);}
 private orders(){return (this.db.prepare('SELECT json FROM orders ORDER BY rowid DESC').all() as {json:string}[]).map(r=>JSON.parse(r.json) as Order);}
 private product(id:string){const p=this.products().find(x=>x.id===id);if(!p)throw Error('Product missing.');return p;}
 private order(id:string){const row=this.db.prepare('SELECT json FROM orders WHERE id=?').get(id) as {json:string}|undefined;if(!row)throw Error('Order missing.');return JSON.parse(row.json) as Order;}
 private saveOrder(o:Order){this.db.prepare('INSERT INTO orders VALUES(?,?) ON CONFLICT(id) DO UPDATE SET json=excluded.json').run(o.id,JSON.stringify(o));}
 private saveProduct(p:Product){this.db.prepare('UPDATE catalog SET json=? WHERE id=?').run(JSON.stringify(p),p.id);}
 prepare(input:Omit<Product,'id'|'sha256'|'status'|'createdAt'>&{data:Buffer}){return this.tx(()=>{if(this.products().some(p=>p.projectId===input.projectId&&p.revisionId===input.revisionId))throw Error('This revision already has a catalog snapshot.');const {data,...fields}=input;const quota=Number(process.env.COMMERCE_ASSET_LIMIT_BYTES||100000000);const used=(this.db.prepare('SELECT COALESCE(SUM(LENGTH(data)),0) AS bytes FROM catalog').get() as {bytes:number}).bytes;if(!Number.isSafeInteger(quota)||quota<1||data.length+used>quota)throw Error('Commerce asset quota exceeded.');const p:Product={...fields,id:randomUUID(),sha256:hash(data),status:'draft',createdAt:new Date().toISOString()};this.db.prepare('INSERT INTO catalog VALUES(?,?,?,?,?)').run(p.id,p.projectId,p.revisionId,JSON.stringify(p),data);return p;});}
 approve(id:string){return this.tx(()=>{const p=this.product(id);if(p.status!=='draft')throw Error('Draft approval required.');for(const old of this.products())if(old.projectId===p.projectId&&old.status==='approved'){old.status='withdrawn';this.saveProduct(old);}p.status='approved';this.saveProduct(p);return p;});}
 withdraw(id:string){return this.tx(()=>{const p=this.product(id);p.status='withdrawn';this.saveProduct(p);});}
 inventory(id:string,stock:number){z.number().int().min(0).max(10000).parse(stock);return this.tx(()=>{const p=this.product(id);if(stock<this.held(id))throw Error('Cannot remove reserved stock.');p.stock=stock;this.saveProduct(p);});}
 private held(id:string){return this.orders().filter(o=>o.status==='reserved').reduce((n,o)=>n+o.items.filter(i=>i.id===id&&!i.digital).reduce((a,i)=>a+i.quantity,0),0);}
 catalog(){return this.products().filter(p=>p.status==='approved').map(p=>({...p,stock:Math.max(0,p.stock-this.held(p.id))}));}
 reserve(input:z.infer<typeof cartSchema>,shippingCents:number,live:boolean,actor=""){const cart=cartSchema.parse(input);if(new Set(cart.map(i=>i.id+':'+i.digital)).size!==cart.length)throw Error('Duplicate cart item.');return this.tx(()=>{if(actor&&this.orders().some(o=>o.actor===hash(actor)&&o.status==="reserved"))throw Error("Existing Checkout still holds inventory.");const items:Item[]=cart.map(i=>{const p=this.product(i.id);if(p.status!=='approved')throw Error('Product unavailable.');if(i.digital&&i.quantity!==1)throw Error('Digital quantity must be one.');if(!i.digital&&p.stock-this.held(p.id)<i.quantity)throw Error('Insufficient stock.');return {...i,name:p.name,revisionId:p.revisionId,priceCents:i.digital?p.digitalPriceCents:p.physicalPriceCents};});z.number().int().min(0).max(100000).parse(shippingCents);const subtotalCents=items.reduce((n,i)=>n+i.priceCents*i.quantity,0),token=randomBytes(32).toString('hex');const o:Order={id:randomUUID(),status:'reserved',items,subtotalCents,shippingCents,taxCents:0,totalCents:subtotalCents+shippingCents,fingerprint:hash(JSON.stringify(items)),sessionId:'',live,tokenHash:hash(token),createdAt:new Date().toISOString(),shipping:null,paymentIntent:'',fulfillment:'',actor:actor?hash(actor):''};this.saveOrder(o);return {order:o,token};});}
 bind(id:string,sessionId:string){return this.tx(()=>{const o=this.order(id);if(o.status!=='reserved')throw Error('Reservation released or paid.');if(o.sessionId&&o.sessionId!==sessionId)throw Error('Session already bound.');o.sessionId=sessionId;this.saveOrder(o);});}
 cancelUnknown(id:string,note:string,now=new Date()){z.string().trim().min(10).max(1000).parse(note);return this.tx(()=>{const o=this.order(id);if(o.status!=='reserved'||o.sessionId)throw Error('Only unknown unbound sessions can be cancelled.');if(now.getTime()-Date.parse(o.createdAt)<35*60000)throw Error('Wait 35 minutes before investigating an unknown Checkout.');o.status='expired';o.fulfillment='Owner confirmed no Stripe session/payment: '+note;this.saveOrder(o);});}
 paid(input:unknown){const s=sessionSchema.parse(input);return this.tx(()=>{const o=this.order(s.metadata.commerce_order_id);const details=s.total_details;if((o.sessionId&&o.sessionId!==s.id)||o.fingerprint!==s.metadata.commerce_fingerprint||o.live!==s.livemode||s.payment_status!=='paid'||s.currency!=='usd'||s.amount_subtotal!==o.subtotalCents||!details||details.amount_discount!==0||details.amount_shipping!==o.shippingCents||s.amount_total!==o.subtotalCents+o.shippingCents+details.amount_tax)throw Error('Payment did not match order.');if(['paid','shipped','revoked'].includes(o.status))return o;if(o.status!=='reserved')throw Error('Stale payment after reservation released.');if(o.shippingCents>0||o.items.some(i=>!i.digital)){const shipping=s.collected_information?.shipping_details||s.shipping_details;if(!shipping)throw Error('Shipping address missing.');o.shipping=shipping;}for(const i of o.items)if(!i.digital){const p=this.product(i.id);if(p.stock<i.quantity)throw Error('Reserved inventory missing.');p.stock-=i.quantity;this.saveProduct(p);}o.sessionId=s.id;o.status='paid';o.totalCents=s.amount_total!;o.taxCents=details.amount_tax;o.paymentIntent=s.payment_intent||'';this.saveOrder(o);return o;});}
 expire(input:unknown){const s=sessionSchema.parse(input);return this.tx(()=>{const o=this.order(s.metadata.commerce_order_id);if((o.sessionId&&o.sessionId!==s.id)||o.fingerprint!==s.metadata.commerce_fingerprint||o.live!==s.livemode)throw Error('Session did not match order.');if(o.status==='reserved'){o.sessionId=s.id;o.status='expired';this.saveOrder(o);}});}
 private authorized(id:string,token:string){const o=this.order(id),actual=hash(token);if(!timingSafeEqual(Buffer.from(actual,'hex'),Buffer.from(o.tokenHash,'hex')))throw Error('Invalid order access.');return o;}
 status(id:string,token:string){const o=this.authorized(id,token);return {id:o.id,status:o.status,items:o.items,totalCents:o.totalCents,fulfillment:o.fulfillment};}
 customerOrders(customerId:string){if(!customerId)throw Error('Customer access required.');return this.orders().filter(o=>o.actor===hash(customerId)).map(o=>({id:o.id,status:o.status,items:o.items,totalCents:o.totalCents,fulfillment:o.fulfillment,createdAt:o.createdAt}));}
 customerDownload(id:string,customerId:string,productId:string){const o=this.order(id);if(!customerId||o.actor!==hash(customerId))throw Error('Invalid customer access.');return this.orderFile(o,productId);}
 download(id:string,token:string,productId:string){return this.orderFile(this.authorized(id,token),productId); }
 private orderFile(o:Order,productId:string){if(!['paid','shipped'].includes(o.status))throw Error('Order must be paid.');const item=o.items.find(i=>i.id===productId&&i.digital);if(!item)throw Error('No digital entitlement.');const row=this.db.prepare('SELECT data FROM catalog WHERE id=?').get(productId) as {data:Uint8Array};const p=this.product(productId),data=Buffer.from(row.data);if(hash(data)!==p.sha256||p.revisionId!==item.revisionId)throw Error('Asset integrity failed.');return {filename:p.filename,data};}
 fulfill(id:string,note:string){z.string().trim().min(1).max(1000).parse(note);return this.tx(()=>{const o=this.order(id);if(o.status!=='paid'||!o.items.some(i=>!i.digital))throw Error('Paid physical order required.');o.status='shipped';o.fulfillment=note;this.saveOrder(o);});}
 reissue(id:string){return this.tx(()=>{const o=this.order(id);if(!['paid','shipped'].includes(o.status))throw Error('Paid order required.');const token=randomBytes(32).toString('hex');o.tokenHash=hash(token);this.saveOrder(o);return token;});}
 revoke(id:string){return this.tx(()=>{const o=this.order(id);if(!['paid','shipped','revoked'].includes(o.status))throw Error('Paid order required.');o.status='revoked';this.saveOrder(o);});}
 refunded(id:string,paymentIntent:string,live:boolean,amount:number){return this.tx(()=>{const o=this.order(id);if(!paymentIntent||o.paymentIntent!==paymentIntent||o.live!==live||!Number.isSafeInteger(amount)||amount<1||amount>o.totalCents||!['paid','shipped','revoked'].includes(o.status))throw Error('Refund did not match order.');o.refundedCents=Math.max(o.refundedCents||0,amount);o.status='revoked';this.saveOrder(o);});}
 overview(){const orders=this.orders();return {products:this.products(),orders:orders.map(({tokenHash,...o})=>{void tokenHash;return o;}),paidRevenueCents:orders.filter(o=>['paid','shipped','revoked'].includes(o.status)).reduce((n,o)=>n+o.totalCents-(o.refundedCents||0),0),reservedOrders:orders.filter(o=>o.status==='reserved').length};}
}
