import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

const dir = mkdtempSync(path.join(tmpdir(), 'mesh-ai-'));
process.env.AI_CENTER_DATABASE_PATH = path.join(dir, 'ai.sqlite');
const { CenterStore } = await import('../lib/ai-center/store.ts');
const { defaultSettings } = await import('../lib/ai-center/policy.ts');
const store = new CenterStore();
try {
  assert.equal(store.snapshot().settings.monthlyLimitCents, 2500);
  assert.equal(store.snapshot().settings.agents.mesh.provider, 'template');
  const free = store.enqueue({agent:'mesh', kind:'outreach', brief:'Ask for project measurements.', key:'free-task-1'});
  assert.equal(store.enqueue({agent:'mesh',kind:'outreach',brief:'Ask for project measurements.',key:'free-task-1'}).id, free.id);
  assert.throws(()=>store.enqueue({agent:'mesh',kind:'outreach',brief:'Changed',key:'free-task-1'}), /different/);
  const claim = store.claim(new Date('2026-10-09T12:00:00Z'));
  assert.equal(claim.id, free.id);
  assert.equal(store.claim(new Date('2026-10-09T12:00:00Z')), null);
  store.finish(free.id, 'Draft only', 0);
  assert.equal(store.snapshot().jobs[0].status, 'review');
  store.decide(free.id, 'approve');
  assert.equal(store.snapshot().jobs[0].status, 'ready');
  assert.throws(()=>store.decide(free.id,'approve'), /pending/);
  const settings = defaultSettings();
  settings.paidEnabled = true;
  settings.monthlyLimitCents = 20;
  settings.agents.mesh = {...settings.agents.mesh, provider:'openai', model:'gpt-4.1-mini', inputCentsPerMillion:400, outputCentsPerMillion:1600, monthlyLimitCents:20};
  store.configure(settings);
  const paid = store.enqueue({agent:'mesh',kind:'review',brief:'Identify bottlenecks.',key:'paid-task-1'});
  assert.equal(paid.status,'spend-review');
  assert.equal(store.claim(new Date('2026-10-09T12:00:00Z')),null);
  store.decide(paid.id,'approve');
  const paidClaim = store.claim(new Date('2026-10-09T12:00:00Z'));
  assert.ok(paidClaim.reservedCents > 0);
  store.fail(paid.id);
  assert.equal(store.snapshot(new Date('2026-10-10')).usage.committedCents, paidClaim.reservedCents);
  settings.monthlyLimitCents = paidClaim.reservedCents;
  store.configure(settings);
  const blocked = store.enqueue({agent:'mesh',kind:'review',brief:'Another draft.',key:'paid-task-2'});
  store.decide(blocked.id,'approve');
  assert.equal(store.claim(new Date('2026-10-10')),null);
  assert.equal(store.snapshot().jobs.find(j=>j.id===blocked.id).status,'queued');
  settings.agents.mesh.monthlyLimitCents = 0;
  settings.monthlyLimitCents = 100;
  store.configure(settings);
  assert.equal(store.claim(new Date('2026-11-01')),null);
  settings.agents.mesh.monthlyLimitCents = 20;
  store.configure(settings);
  assert.equal(store.claim(new Date('2026-11-01')).id, blocked.id);
  store.finish(blocked.id,'New month draft',1);
  assert.equal(store.snapshot(new Date('2026-11-02')).usage.committedCents,1);
  assert.equal(store.snapshot(new Date('2026-10-02')).usage.committedCents,paidClaim.reservedCents);
  assert.throws(()=>store.configure({...settings,monthlyLimitCents:-1}));
  const olderReview = blocked.id;
  for(let i=0;i<205;i++)store.enqueue({agent:'mesh',kind:'review',brief:'Backlog fixture',key:`backlog-${i}`});
  assert.equal(store.snapshot().jobs.length,200);
  assert.ok(store.snapshot().approvals.some(j=>j.id===olderReview),'Old pending approvals must remain reachable');
  console.log('AI center transactional policy checks passed.');
} finally { store.close(); rmSync(dir,{recursive:true,force:true}); }
