import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
const dir=mkdtempSync(path.join(tmpdir(),'ai-metrics-'));
process.env.DATABASE_PATH=path.join(dir,'business.sqlite');
const { businessOverview }=await import('../lib/ai-center/metrics.ts');
try {
  assert.equal(businessOverview().available,false);
  assert.equal(existsSync(process.env.DATABASE_PATH),false);
  const db=new DatabaseSync(process.env.DATABASE_PATH);
  db.exec('CREATE TABLE app_records(collection TEXT,id TEXT,json TEXT,updated_at TEXT)');
  const put=(collection,value)=>db.prepare('INSERT INTO app_records VALUES(?,?,?,?)').run(collection,value.id,JSON.stringify(value),'2026-10-09');
  put('requests',{id:'r1',requestCode:'REQ-TEST',status:'new',createdAt:'2026-10-09',updatedAt:'2026-10-09',name:'Private name',email:'private@example.com',description:'Private text'});
  put('quotes',{id:'q1',requestId:'r1',revision:1,status:'draft',totalCents:10000,updatedAt:'2026-10-09'});
  put('customers',{id:'c1',passwordHash:'SECRET'});
  put('requests',{id:'r2',requestCode:'REQ-DECLINED',status:'declined',createdAt:'2026-10-09',updatedAt:'2026-10-09'});
  put('requests',{id:'r3',requestCode:'REQ-DONE',status:'completed',createdAt:'2026-10-09',updatedAt:'2026-10-09'});
  put('quotes',{id:'q2',requestId:'r3',revision:1,status:'deposit-paid',totalCents:10000,updatedAt:'2026-10-09',payments:[{amountCents:5000,processorAmountCents:5200}],refunds:[{amountCents:200,status:'succeeded'},{amountCents:300,status:'failed'}]});
  put('final-invoices',{id:'i1',requestId:'r3',amountPaidCents:5000});
  db.close();
  const value=businessOverview();
  assert.equal(value.available,true);
  assert.equal(value.counts.requests,3);
  assert.equal(value.counts.activeRequests,1);
  assert.equal(value.counts.customers,1);
  assert.equal(value.counts.quotes,2);
  assert.ok(!JSON.stringify(value).includes('SECRET'));
  assert.ok(!JSON.stringify(value).includes('private@example'));
  assert.ok(!JSON.stringify(value).includes('Private text'));
  assert.equal(value.profitability.completed.revenueCents,0);
  assert.equal(value.profitability.completed.uncostedCount,1);
  assert.equal(value.recordedNetPaymentsCents,10000);
  const after=new DatabaseSync(process.env.DATABASE_PATH,{readOnly:true});
  assert.equal(after.prepare('SELECT count(*) AS n FROM app_records').get().n,7);
  assert.equal(after.prepare("SELECT count(*) AS n FROM sqlite_master WHERE type='table'").get().n,1);
  after.close();
  console.log('AI business metrics read-only and privacy checks passed.');
} finally {rmSync(dir,{recursive:true,force:true});}
