import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
const {CommerceStore,commercePath}=await import('../lib/commerce/store.ts');
const dir=mkdtempSync(path.join(tmpdir(),'commerce-'));
const store=new CommerceStore(path.join(dir,'commerce.sqlite'));
try {
 const previousCommerce=process.env.COMMERCE_DATABASE_PATH,previousMarketplace=process.env.MARKETPLACE_DATABASE_PATH;process.env.COMMERCE_DATABASE_PATH=path.join(dir,'collision.sqlite');process.env.MARKETPLACE_DATABASE_PATH=path.join(dir,'collision.sqlite');assert.throws(()=>commercePath(),/separate database/);if(previousCommerce===undefined)delete process.env.COMMERCE_DATABASE_PATH;else process.env.COMMERCE_DATABASE_PATH=previousCommerce;if(previousMarketplace===undefined)delete process.env.MARKETPLACE_DATABASE_PATH;else process.env.MARKETPLACE_DATABASE_PATH=previousMarketplace;
 const product=store.prepare({projectId:'project',revisionId:'rev1',name:'Original tray',description:'Tested tray',license:'Personal use',physicalPriceCents:1200,digitalPriceCents:300,costCents:400,stock:1,filename:'tray.stl',data:Buffer.from('immutable STL'),photoUrl:'https://example.com/tray.jpg'});
 assert.equal(store.catalog().length,0);store.approve(product.id);assert.equal(store.catalog().length,1);
 const checkout=store.reserve([{id:product.id,digital:false,quantity:1}],200,false);
 assert.throws(()=>store.reserve([{id:product.id,digital:false,quantity:1}],200,false),/stock/);
 store.bind(checkout.order.id,'cs_test_1');
 const payment={id:'cs_test_1',payment_status:'paid',amount_subtotal:1200,amount_total:1400,currency:'usd',livemode:false,shipping_details:{name:'Test Buyer',address:{country:'US'}},total_details:{amount_shipping:200,amount_tax:0,amount_discount:0},metadata:{commerce_order_id:checkout.order.id,commerce_fingerprint:checkout.order.fingerprint}};
 assert.throws(()=>store.paid({...payment,amount_subtotal:1}),/match/);
 assert.throws(()=>store.paid({...payment,id:'cs_other'}),/match/);
 assert.throws(()=>store.paid({...payment,currency:'eur'}),/match/);
 assert.throws(()=>store.paid({...payment,livemode:true}),/match/);
 assert.throws(()=>store.paid({...payment,metadata:{...payment.metadata,commerce_fingerprint:'wrong'}}),/match/);
 assert.throws(()=>store.paid({...payment,payment_status:'unpaid'}),/match/);
 store.paid(payment);store.paid(payment);assert.equal(store.overview().paidRevenueCents,1400);
 assert.throws(()=>store.status(checkout.order.id,'wrong'),/access/);
 assert.equal(store.status(checkout.order.id,checkout.token).status,'paid');
 assert.throws(()=>store.download(checkout.order.id,checkout.token,product.id),/digital/);
 const digital=store.reserve([{id:product.id,digital:true,quantity:1}],0,false);store.bind(digital.order.id,'cs_test_2');
 assert.throws(()=>store.download(digital.order.id,digital.token,product.id),/paid/);
 store.paid({...payment,id:'cs_test_2',payment_intent:'pi_digital',amount_subtotal:300,amount_total:300,total_details:{amount_shipping:0,amount_tax:0,amount_discount:0},metadata:{commerce_order_id:digital.order.id,commerce_fingerprint:digital.order.fingerprint}});
 assert.equal(store.download(digital.order.id,digital.token,product.id).data.toString(),'immutable STL');
 const physical=store.prepare({projectId:'second',revisionId:'rev1',name:'Second tray',description:'Tested tray',license:'Personal use',physicalPriceCents:1200,digitalPriceCents:300,costCents:400,stock:1,filename:'tray.stl',data:Buffer.from('second STL'),photoUrl:'https://example.com/tray.jpg'});
 store.approve(physical.id);
 const held=store.reserve([{id:physical.id,digital:false,quantity:1}],200,false);store.bind(held.order.id,'cs_expire');
 assert.throws(()=>store.expire({...payment,id:'other',metadata:{commerce_order_id:held.order.id,commerce_fingerprint:held.order.fingerprint}}),/match/);
 store.expire({...payment,id:'cs_expire',metadata:{commerce_order_id:held.order.id,commerce_fingerprint:held.order.fingerprint}});
 assert.equal(store.catalog().find(p=>p.id===physical.id).stock,1);
 assert.throws(()=>store.paid({...payment,id:'cs_expire',metadata:{commerce_order_id:held.order.id,commerce_fingerprint:held.order.fingerprint}}),/Stale/);
 const recovery=store.reissue(digital.order.id);assert.throws(()=>store.status(digital.order.id,digital.token),/access/);assert.equal(store.status(digital.order.id,recovery).status,'paid');
 store.revoke(digital.order.id);assert.throws(()=>store.download(digital.order.id,recovery,product.id),/paid/);
 assert.equal(store.overview().paidRevenueCents,1700,'Revoking access must not erase recorded payments');
 const config=await import('../lib/commerce/config.ts');assert.throws(()=>config.checkoutConfiguration(false),/launch/);
 process.env.COMMERCE_CATALOG_ENABLED='true';process.env.COMMERCE_CHECKOUT_ENABLED='true';process.env.COMMERCE_TAX_REVIEWED='true';assert.throws(()=>config.checkoutConfiguration(true),/shipping/);process.env.COMMERCE_SHIPPING_COUNTRIES='US';process.env.COMMERCE_SHIPPING_RATE_CENTS='500';assert.equal(config.checkoutConfiguration(true).shippingCents,500);
 store.withdraw(product.id);assert.equal(store.catalog().some(p=>p.id===product.id),false);
 assert.throws(()=>store.download(digital.order.id,recovery,product.id),/paid/);
 const results=await Promise.all(Array.from({length:6},()=>new Promise((resolve,reject)=>{const script=`const {CommerceStore}=await import('./lib/commerce/store.ts');const s=new CommerceStore(${JSON.stringify(path.join(dir,'commerce.sqlite'))});try{s.reserve([{id:${JSON.stringify(physical.id)},digital:false,quantity:1}],200,false);console.log('HELD');}catch{console.log('BLOCKED');}finally{s.close();}`;const child=spawn(process.execPath,['--experimental-strip-types','--experimental-loader','./tests/server-only-loader.mjs','--input-type=module','-e',script],{env:process.env});let out='';child.stdout.on('data',b=>out+=b);child.on('error',reject);child.on('exit',code=>code===0?resolve(out):reject(Error('Reservation child failed')));})));assert.equal(results.filter(s=>s.includes('HELD')).length,1);
 process.env.COMMERCE_ASSET_LIMIT_BYTES='1';assert.throws(()=>store.prepare({projectId:'quota',revisionId:'rev',name:'Quota',description:'Q',license:'Personal use',physicalPriceCents:1200,digitalPriceCents:300,costCents:400,stock:0,filename:'tray.stl',data:Buffer.from('third STL'),photoUrl:'https://example.com/tray.jpg'}),/quota/);delete process.env.COMMERCE_ASSET_LIMIT_BYTES;
 const ambiguous=store.reserve([{id:physical.id,digital:true,quantity:1}],0,false,'buyer');assert.throws(()=>store.reserve([{id:physical.id,digital:true,quantity:1}],0,false,'buyer'),/Existing/);
 assert.throws(()=>store.cancelUnknown(ambiguous.order.id,'Checked Stripe; no matching session/payment.'),/35 minutes/);
 store.cancelUnknown(ambiguous.order.id,'Checked Stripe; no matching session/payment.',new Date(Date.parse(ambiguous.order.createdAt)+36*60000));assert.throws(()=>store.bind(ambiguous.order.id,'cs_late'),/released/);
 assert.throws(()=>store.paid({...payment,id:'cs_late',amount_subtotal:300,amount_total:300,total_details:{amount_shipping:0,amount_tax:0,amount_discount:0},metadata:{commerce_order_id:ambiguous.order.id,commerce_fingerprint:ambiguous.order.fingerprint}}),/Stale/);
 assert.equal(store.reserve([{id:physical.id,digital:true,quantity:1}],0,false,'buyer').order.status,'reserved');
 assert.throws(()=>store.refunded(digital.order.id,'pi_wrong',false,100),/match/);store.refunded(digital.order.id,'pi_digital',false,100);store.refunded(digital.order.id,'pi_digital',false,100);assert.equal(store.overview().paidRevenueCents,1600);assert.throws(()=>store.download(digital.order.id,recovery,product.id),/paid/);
 const accountOrder=store.overview().orders.find(o=>o.status==='reserved'&&o.actor);store.bind(accountOrder.id,'cs_account');store.paid({...payment,id:'cs_account',amount_subtotal:300,amount_total:300,total_details:{amount_shipping:0,amount_tax:0,amount_discount:0},metadata:{commerce_order_id:accountOrder.id,commerce_fingerprint:accountOrder.fingerprint}});
 assert.equal(store.customerOrders('buyer').some(o=>o.id===accountOrder.id),true);assert.equal(store.customerOrders('other').length,0);assert.throws(()=>store.customerDownload(accountOrder.id,'other',physical.id),/access/);assert.equal(store.customerDownload(accountOrder.id,'buyer',physical.id).data.toString(),'second STL');
 const {boundedText}=await import('../lib/commerce/http.ts');assert.equal(await boundedText(new Request('https://example.com',{method:'POST',body:'small'}),10),'small');await assert.rejects(boundedText(new Request('https://example.com',{method:'POST',body:'too large'}),4),/large/);
 console.log('Commerce approval, stock, payment binding, duplicate and download authorization passed.');
} finally {store.close();rmSync(dir,{recursive:true,force:true});}
