import assert from 'node:assert/strict';
import { rm } from 'node:fs/promises';
const db=`/tmp/meshharbor-cost-closeout-${process.pid}.sqlite`;
process.env.DATABASE_PATH=db;
await rm(db,{force:true});
const store=await import('../lib/quote-cost-store.ts');
const estimate={id:'quote-1:r1:estimate',requestId:'req-1',requestCode:'REQ-ONE',quoteId:'quote-1',quoteRevision:1,status:'estimate',materialLines:[{id:'m1',catalogItemId:'pla-basic-refill',grams:200,displayName:'PLA Basic',costSource:'actual-average',costPerGramMicros:1500000,extendedCostCents:300}],machineHours:4,machineHourlyCostCents:300,designHours:1,designHourlyCostCents:1000,laborHours:.5,laborHourlyCostCents:2000,postProcessingHours:.25,postProcessingHourlyCostCents:1600,packagingCostCents:100,localDeliveryInternalCostCents:0,miscellaneousCostCents:50,paymentFeeCents:300,shippingInternalCostCents:0,nonPaymentDirectCostCents:4050,directCostCents:4350,quotedRevenueCents:9000,contributionProfitCents:4650,contributionMarginBasisPoints:5167,targetMarginBasisPoints:4000,suggestedPriceCents:7000,priceMeetsTarget:true,costingSourceSummary:'actual-average',createdAt:'2026-09-25T12:00:00.000Z',updatedAt:'2026-09-25T12:00:00.000Z',finalizedAt:''};
await store.saveCostSnapshot(estimate);
const actual=await store.createActualFromEstimate('req-1',1);
assert.equal(actual.id,'quote-1:r1:actual');
assert.equal(actual.status,'actual');
assert.equal(actual.machineHours,4);
await store.saveCostSnapshot({...actual,machineHours:5});
const finalized=await store.finalizeActualCost(actual.id);
assert.equal(finalized.status,'finalized');
assert.ok(finalized.finalizedAt);
await assert.rejects(()=>store.saveCostSnapshot({...finalized,machineHours:6}),/reopened/i);
const reopened=await store.reopenActualCost(actual.id);
assert.equal(reopened.status,'actual');
assert.equal(reopened.finalizedAt,'');
const saved=await store.saveCostSnapshot({...reopened,machineHours:6});
assert.equal(saved.machineHours,6);
await rm(db,{force:true});
console.log('Cost closeout checks passed.');
