import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
const dir=mkdtempSync(path.join(tmpdir(),'etsy-fixtures-'));
process.env.MARKETPLACE_DATABASE_PATH=path.join(dir,'marketplace.sqlite');
process.env.MARKETPLACE_TOKEN_KEY='ab'.repeat(32);
process.env.ETSY_APP_KEY='fixture-app';process.env.ETSY_SHARED_SECRET='fixture-secret';
process.env.ETSY_REDIRECT_URI='https://owner.example/api/owner/marketplace/callback';
process.env.ETSY_ENABLED='true';
const {MarketplaceStore}=await import('../lib/marketplace/store.ts');
const {beginAuthorization,completeAuthorization,readOwnSales,observeMarket,exportListing}=await import('../lib/marketplace/etsy.ts');
const {runMarketplaceResearch}=await import('../lib/marketplace/research.ts');
const {evidenceFromObservation}=await import('../lib/marketplace/evidence.ts');
const {readLimitedBody}=await import('../lib/marketplace/body.ts');
const store=new MarketplaceStore();
const token={access_token:'123.fixtureAccessSecret',refresh_token:'123.fixtureRefreshSecret',token_type:'Bearer',expires_in:3600,scope:'shops_r listings_r transactions_r'};
let calls=[];
const authFetch=async(url,options)=>{
 calls.push({url,options});
 if(url.endsWith('/oauth/token'))return Response.json(token);
 assert.match(url,/\/users\/123\/shops$/);
 return Response.json({shop_id:456,user_id:123,shop_name:'MeshHarbor3D'});
};
try{
 let canceled=false;const hostileBody=new ReadableStream({pull(controller){controller.enqueue(new Uint8Array(1024));},cancel(){canceled=true;}});
 await assert.rejects(()=>readLimitedBody(new Request('https://owner.example',{method:'POST',body:hostileBody,duplex:'half'}),8000),/too large/);assert.equal(canceled,true);
 const auth=beginAuthorization(store,'owner-session',0),url=new URL(auth.url);
 assert.equal(url.origin,'https://www.etsy.com');assert.equal(url.searchParams.get('code_challenge_method'),'S256');
 const state=url.searchParams.get('state');
 await assert.rejects(()=>completeAuthorization(store,'other-owner',state,'fixture-code',authFetch,1),/Authorization/);
 assert.equal(calls.length,0);
 await completeAuthorization(store,'owner-session',state,'fixture-code',authFetch,1);
 const exchange=new URLSearchParams(calls[0].options.body);
 assert.equal(createHash('sha256').update(exchange.get('code_verifier')).digest('base64url'),url.searchParams.get('code_challenge'));
 assert.equal(url.searchParams.get('scope'),'shops_r listings_r transactions_r');
 await assert.rejects(()=>completeAuthorization(store,'owner-session',state,'fixture-code',authFetch,2),/Authorization/);
 assert.ok(!JSON.stringify(store.status(2)).includes('Secret'));
 assert.ok(!readFileSync(process.env.MARKETPLACE_DATABASE_PATH).includes(Buffer.from('fixtureAccessSecret')));
 assert.ok(!readFileSync(process.env.MARKETPLACE_DATABASE_PATH+'-wal').includes(Buffer.from('fixtureRefreshSecret')));
 const expired=beginAuthorization(store,'owner-session',0);
 await assert.rejects(()=>completeAuthorization(store,'owner-session',new URL(expired.url).searchParams.get('state'),'code',authFetch,600001),/Authorization/);
 calls=[];
 const sales=await readOwnSales(store,{days:30,maxPages:2},async(url,options)=>{
  calls.push({url,options});assert.equal(new URL(url).host,'api.etsy.com');assert.equal(options.method,'GET');
  assert.equal(options.headers['x-api-key'],'fixture-app:fixture-secret');
  return Response.json({count:300,results:Array.from({length:100},(_,i)=>({receipt_id:Number(new URL(url).searchParams.get('offset'))+i+1,is_paid:true,status:'paid',buyer_email:'PRIVATE',transactions:Array.from({length:2},()=>({transaction_id:Number(new URL(url).searchParams.get('offset'))+i+1,listing_id:987,title:'Fixture desk stand',quantity:2,price:{amount:500,divisor:100,currency_code:'USD'}}))}))});
 },1000);
 assert.equal(calls.length,2);assert.equal(sales.truncated,true);assert.equal(sales.rankings[0].units,400);assert.equal(sales.rankings[0].itemGrossCents,200000);assert.ok(!JSON.stringify(sales).includes('PRIVATE'));assert.equal(sales.windowDays,30);
 const observations=await observeMarket(store,'desk organizer',async(url)=>{
  assert.equal(new URL(url).host,'api.etsy.com');
  return Response.json({count:1,results:[{listing_id:1,title:'<script>hostile</script>',url:'https://evil.example/steal',num_favorers:2,price:{amount:1500,divisor:100,currency_code:'USD'},quantity:500}]});
 },200000);
 assert.equal(observations.items[0].url,'https://www.etsy.com/listing/1');assert.equal(observations.items[0].sales,undefined);assert.match(observations.limitations,/not.*sales/i);
 const evidence=evidenceFromObservation({...observations,query:'x'.repeat(120),items:Array.from({length:25},()=>({...observations.items[0],id:Number.MAX_SAFE_INTEGER,priceCents:100000000000,favorites:Number.MAX_SAFE_INTEGER}))});
 assert.ok(evidence.signal.length<=2000);assert.match(evidence.signal,/not verified competitor item sales/);assert.ok(!evidence.signal.includes('<script>'));
 const salesEvidence=evidenceFromObservation(sales);assert.match(salesEvidence.signal,/not net revenue|Not net revenue/);assert.ok(!salesEvidence.signal.includes('Fixture desk stand'));
 await assert.rejects(()=>observeMarket(store,'x',async()=>Response.json({count:1,results:[{listing_id:-1,title:'bad'}]}),400000),/Invalid/);
 const expiredStore=store.token();assert.ok(expiredStore.expiresAt>0);
 const project={id:'p',version:2,stage:'release',name:'Tested stand',revisions:[{id:'r',filename:'stand.stl',sha256:'hash',tests:[{passed:true}]}],release:{revisionId:'r',description:'Original tested stand',physicalPriceCents:2000,digitalPriceCents:500,costCents:500,stock:3,license:'Personal use',original:true}};
 const approved={projectId:'p',key:'project-p-2-listing',kind:'listing',status:'ready',output:'Owner-reviewed description'};
 assert.equal(exportListing(project,[approved],'physical').priceCents,2000);
 assert.throws(()=>exportListing({...project,release:null},[approved],'physical'),/release/);
 assert.throws(()=>exportListing(project,[{...approved,status:'review'}],'digital'),/approved/);
 assert.throws(()=>exportListing({...project,revisions:[{...project.revisions[0],tests:[{passed:false}]}]},[approved],'physical'),/tested/);
 assert.throws(()=>exportListing({...project,version:3},[approved],'physical'),/approved/);
 assert.equal(await runMarketplaceResearch(async()=>{throw Error('must stay disabled');},700000),null);
 process.env.ETSY_RESEARCH_ENABLED='true';process.env.ETSY_RESEARCH_KEYWORDS='desk organizer,small PLA stand';
 let sweeps=0;const sweepFetch=async()=>{sweeps++;return Response.json({count:0,results:[]});};
 assert.equal((await runMarketplaceResearch(sweepFetch,700000)).kind,'market');
 assert.equal(await runMarketplaceResearch(sweepFetch,700001),null);assert.equal(sweeps,1);
 let refreshed=0;const expiryRead=await readOwnSales(store,{days:30,maxPages:1},async(url,options)=>{
  assert.equal(options.redirect,'error');assert.ok(options.signal);
  if(url.endsWith('/oauth/token')){refreshed++;assert.equal(new URLSearchParams(options.body).get('grant_type'),'refresh_token');return Response.json({...token,access_token:'123.refreshedSecret',refresh_token:'123.newRefreshSecret'});}
  return Response.json({count:2,results:[{receipt_id:700,is_paid:false,status:'open',transactions:[{transaction_id:700,listing_id:1,title:'Unpaid fixture',quantity:1,price:{amount:1,divisor:100,currency_code:'USD'}}]},{receipt_id:701,is_paid:true,status:'canceled',transactions:[]}]});
 },4000000);
 assert.equal(refreshed,1);assert.equal(expiryRead.rankings.length,0);assert.ok(!JSON.stringify(store.status(4000000)).includes('Secret'));
 process.env.ETSY_EXPECTED_SHOP_NAME='DifferentShop';
 await assert.rejects(()=>readOwnSales(store,{days:30,maxPages:1},async()=>{throw Error('never fetch');},4500000),/configured owner shop/);
 delete process.env.ETSY_EXPECTED_SHOP_NAME;
 await assert.rejects(()=>readOwnSales(store,{days:30,maxPages:1},async()=>Response.json({...token,access_token:'999.wrongUserSecret'}),8000000),/identity/);
 assert.equal(store.token().accessToken,'123.refreshedSecret');
 await assert.rejects(()=>readOwnSales(store,{days:30,maxPages:4},async()=>{throw Error('never fetch');},9000000));
 const failedSweep=await runMarketplaceResearch(async()=>{throw Error('secret raw upstream body');},87100000);
 assert.equal(failedSweep.kind,'research-failure');
 assert.ok(!JSON.stringify(store.reports()).includes('secret raw upstream body'));
 assert.equal(await runMarketplaceResearch(sweepFetch,87100001),null);
 const race=beginAuthorization(store,'owner-session',90000000);
 await assert.rejects(()=>completeAuthorization(store,'owner-session',new URL(race.url).searchParams.get('state'),'fixture-race-code',async(url,options)=>{if(url.endsWith('/oauth/token')){store.disconnect();return Response.json(token);}return authFetch(url,options);},90000001),/removed|changed/);
 assert.equal(store.status(90000002).connected,false);
 store.disconnect();assert.equal(store.status(1000).connected,false);
 console.log('Etsy isolated fixtures: OAuth/PKCE, replay/expiry, token encryption/redaction, bounded reads, honest observations and approved-tested export passed. No live Etsy calls.');
}finally{store.close();rmSync(dir,{recursive:true,force:true});}
