import { NextRequest,NextResponse } from 'next/server';
import { z } from 'zod';
import { requestIsOwner } from '@/lib/owner-auth';
import { sameOrigin } from '@/lib/owner-api';
import { ensureBambuCatalogSeeded,findBambuCatalogItem,readBambuCatalog,upsertBambuCatalogItem } from '@/lib/pricing-store';
import { costPerGramMicros } from '@/lib/pricing-math';
import { requestIpHash,writeAudit } from '@/lib/audit-log';
const schema=z.object({id:z.string().min(1).max(120),msrpCents:z.number().int().min(0).max(100000).optional(),netWeightGrams:z.number().int().min(1).max(10000).optional(),manualFallbackCostPerGramMicros:z.number().int().min(0).max(1_000_000_000).optional(),active:z.boolean().optional(),notes:z.string().max(500).optional()}).strict();
export async function GET(request:NextRequest){if(!await requestIsOwner(request))return NextResponse.json({message:'Sign in required.'},{status:401});await ensureBambuCatalogSeeded();return NextResponse.json({catalog:await readBambuCatalog()},{headers:{'Cache-Control':'no-store'}});}
export async function PATCH(request:NextRequest){if(!await requestIsOwner(request))return NextResponse.json({message:'Sign in required.'},{status:401});if(!sameOrigin(request))return NextResponse.json({message:'Request origin was not accepted.'},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:'Check the Bambu catalog values.'},{status:400});await ensureBambuCatalogSeeded();const current=await findBambuCatalogItem(parsed.data.id);if(!current)return NextResponse.json({message:'Bambu catalog item not found.'},{status:404});const netWeightGrams=parsed.data.netWeightGrams??current.netWeightGrams;const msrpCents=parsed.data.msrpCents??current.msrpCents;const item=await upsertBambuCatalogItem({...current,...parsed.data,netWeightGrams,msrpCents,msrpCostPerGramMicros:msrpCents>0?costPerGramMicros(msrpCents,netWeightGrams):0});await writeAudit({actor:'owner',actorId:'owner',action:'bambu-catalog-updated',targetType:'pricing-material',targetId:item.id,summary:`Updated ${item.displayName} pricing reference.`,ipHash:requestIpHash(request)});return NextResponse.json({item,message:'Bambu catalog item saved.'});}
