"use client";
import { useState } from "react";
import type { ShippingSelection } from "@/lib/quote-types";

type Rate={id:string;carrier:"USPS"|"UPS"|"FedEx";service:string;rateCents:number;deliveryDays:number|null;deliveryDate:string};
type Address={name:string;street1:string;street2:string;city:string;state:string;zip:string;country:string};
function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);}
async function jsonFetch(url:string,init:RequestInit){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),15000);try{return await fetch(url,{...init,signal:controller.signal});}finally{window.clearTimeout(timer);}}
export function CustomerShippingSelector({quoteId,existing,customerName,onChanged,onMessage}:{quoteId:string;existing:ShippingSelection|null;customerName:string;onChanged:()=>Promise<void>;onMessage:(message:string)=>void}){
  const [open,setOpen]=useState(!existing);const [busy,setBusy]=useState(false);const [rates,setRates]=useState<Rate[]>([]);const [shipmentId,setShipmentId]=useState("");
  const [address,setAddress]=useState<Address>(existing?.address||{name:customerName,street1:"",street2:"",city:"",state:"",zip:"",country:"US"});
  function update(key:keyof Address,value:string){setAddress(current=>({...current,[key]:value}));}
  async function getRates(){setBusy(true);onMessage("");try{const r=await jsonFetch(`/api/account/quotes/${quoteId}/shipping-rates`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(address)});const j=await r.json() as {shipmentId?:string;rates?:Rate[];message?:string};if(!r.ok||!j.shipmentId)throw new Error(j.message||"Could not calculate live rates.");setShipmentId(j.shipmentId);setRates(j.rates||[]);}catch(e){onMessage(e instanceof Error?e.message:"Could not calculate live rates.");}finally{setBusy(false);}}
  async function select(rate:Rate){setBusy(true);onMessage("");try{const r=await jsonFetch(`/api/account/quotes/${quoteId}/shipping-selection`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({selection:{shipmentId,rateId:rate.id},address})});const j=await r.json() as {message?:string};if(!r.ok)throw new Error(j.message||"Could not save shipping choice.");onMessage(j.message||"Shipping selected.");setOpen(false);setRates([]);await onChanged();}catch(e){onMessage(e instanceof Error?e.message:"Could not save shipping choice.");}finally{setBusy(false);}}
  const grouped=rates.reduce<Record<string,Rate[]>>((acc,rate)=>{(acc[rate.carrier]||=[]).push(rate);return acc;},{});
  return <div className="customer-shipping-selector">
    <div className="customer-shipping-heading"><div><strong>Shipping carrier & service</strong><span>Choose from live USPS, UPS, and FedEx rates for your delivery address.</span></div>{existing&&!open&&<button className="button button-secondary button-small" type="button" onClick={()=>setOpen(true)}>Change Shipping</button>}</div>
    {existing&&!open&&<div className="shipping-selected-card"><div><b>{existing.carrier}</b><strong>{existing.service}</strong><span>{existing.deliveryDays?`${existing.deliveryDays} business day${existing.deliveryDays===1?"":"s"}`:existing.deliveryDate?`Estimated ${existing.deliveryDate}`:"Carrier estimate shown at checkout"}</span></div><strong>{money(existing.rateCents)}</strong></div>}
    {open&&<><div className="shipping-address-grid"><label><span>Name</span><input value={address.name} onChange={e=>update("name",e.target.value)}/></label><label className="wide"><span>Street address</span><input value={address.street1} onChange={e=>update("street1",e.target.value)}/></label><label><span>Apt / suite</span><input value={address.street2} onChange={e=>update("street2",e.target.value)}/></label><label><span>City</span><input value={address.city} onChange={e=>update("city",e.target.value)}/></label><label><span>State</span><input value={address.state} onChange={e=>update("state",e.target.value)} placeholder="NC"/></label><label><span>ZIP code</span><input value={address.zip} onChange={e=>update("zip",e.target.value)} inputMode="numeric"/></label></div><div className="shipping-rate-actions"><button className={`button button-small ${busy?"is-loading":""}`} disabled={busy} type="button" onClick={()=>void getRates()}>{busy?"Getting live rates…":rates.length?"Refresh Live Rates":"Get Live Rates"}</button>{existing&&<button className="text-button" disabled={busy} type="button" onClick={()=>setOpen(false)}>Cancel</button>}</div>
      {rates.length>0&&<div className="shipping-rate-groups">{["USPS","UPS","FedEx"].map(carrier=>grouped[carrier]?.length?<section key={carrier}><div className="shipping-carrier-heading"><strong>{carrier}</strong><span>{grouped[carrier].length} option{grouped[carrier].length===1?"":"s"}</span></div><div className="shipping-rate-list">{grouped[carrier].map(rate=><button type="button" disabled={busy} onClick={()=>void select(rate)} key={rate.id}><div><strong>{rate.service}</strong><span>{rate.deliveryDays?`Estimated ${rate.deliveryDays} business day${rate.deliveryDays===1?"":"s"}`:rate.deliveryDate?`Estimated ${rate.deliveryDate}`:"Delivery estimate unavailable"}</span></div><b>{money(rate.rateCents)}</b></button>)}</div></section>:null)}</div>}
    </>}
    <small className="shipping-private-note">Your delivery address is private account/order information. It is never shown on the public Queue.</small>
  </div>;
}
