'use client';
import {useCallback,useEffect,useState} from 'react';
import type {ProductProject} from '@/lib/ai-center/projects';
import type {Publication} from '@/lib/marketplace/publication';
import styles from './AiBusinessCenter.module.css';
type Snapshot={writesEnabled:boolean;publications:Publication[]};
export function EtsyPublication({projects}:{projects:ProductProject[]}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[projectId,setProjectId]=useState(''),[format,setFormat]=useState<'physical'|'digital'>('physical'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[taxonomy,setTaxonomy]=useState(''),[shipping,setShipping]=useState(''),[processing,setProcessing]=useState(''),[returns,setReturns]=useState(''),[photo,setPhoto]=useState<File|null>(null),[rights,setRights]=useState(false),[stock,setStock]=useState(false),[policies,setPolicies]=useState(false),[approval,setApproval]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/owner/marketplace/publications',{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.message||'Publication status unavailable.');setData(v);}catch(e){setError(e instanceof Error?e.message:'Publication unavailable.');}},[]);
 useEffect(()=>{void load();},[load]);
 const candidates=projects.filter(p=>p.stage==='release'),project=projects.find(p=>p.id===projectId);
 function choose(id:string){const p=projects.find(p=>p.id===id);setProjectId(id);setTitle(p?.name||'');setDescription(p?.release?.description||'');setRights(false);setStock(false);setPolicies(false);}
 async function authorize(){setBusy(true);setError('');try{const r=await fetch('/api/owner/marketplace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'connect',writeAccess:true})}),v=await r.json();if(!r.ok)throw Error(v.message);const u=new URL(v.url);if(u.origin!=='https://www.etsy.com'||u.pathname!=='/oauth/connect')throw Error('Invalid authorization URL.');window.location.assign(u.toString());}catch(e){setError(e instanceof Error?e.message:'Authorization unavailable.');}finally{setBusy(false);}}
 async function prepare(){if(!project||!photo)return;setBusy(true);setError('');setMessage('');try{const form=new FormData();form.set('reference',JSON.stringify({projectId:project.id,version:project.version}));form.set('package',JSON.stringify({format,title,description,priceCents:format==='physical'?project.release!.physicalPriceCents:project.release!.digitalPriceCents,allocatedQuantity:1,taxonomyId:Number(taxonomy),shippingProfileId:format==='physical'?Number(shipping):null,readinessStateId:format==='physical'?Number(processing):null,returnPolicyId:format==='physical'?Number(returns):null,whenMade:'2020_2026',originalPhoto:rights,stockAllocated:stock,rightsReviewed:rights,policiesReviewed:policies}));form.set('photo',photo);const r=await fetch('/api/owner/marketplace/publications',{method:'POST',body:form}),v=await r.json();if(!r.ok)throw Error(v.message);setMessage('Immutable preview prepared. Review every field and fee policy below before approving publication.');setApproval('');await load();}catch(e){setError(e instanceof Error?e.message:'Preview unavailable.');}finally{setBusy(false);}}
 async function publish(intent:Publication){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/owner/marketplace/publications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:intent.id,hash:intent.hash,publish:true,fees:true,stock:true})}),v=await r.json();if(!r.ok)throw Error(v.message);setMessage(v.publication.status==='published'?'Etsy returned an active listing. Verify its content, quantity and fees in Etsy.':'Outcome uncertain. Reconcile Etsy drafts, listings and fees manually. This package cannot be retried.');setApproval('');await load();}catch(e){setError(e instanceof Error?e.message:'Publication unavailable.');}finally{setBusy(false);}}
 return <article className={styles.card}><h2>Owner-approved Etsy publication</h2><p>Disabled until the owner configures and approves Etsy write access. Every publication needs a passing current print revision, original release declaration, approved listing draft and a fresh preview. Nothing is published by an agent or background worker.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}<p role="status" aria-live="polite">{message}</p>
 <p><strong>{data?.writesEnabled?'Write adapter enabled; each listing still requires approval':'Write adapter disabled: ETSY_WRITES_ENABLED must be explicitly configured after review.'}</strong></p><button type="button" disabled={busy||!data?.writesEnabled} onClick={()=>void authorize()}>Authorize Etsy listing write access</button><p>This separate grant adds only listings_w to the existing read scopes. No payment, message, refund or shop-setting scope is requested.</p>
 <form onSubmit={e=>{e.preventDefault();void prepare();}}><div className={styles.grid}><label>Tested release<select required value={projectId} onChange={e=>choose(e.target.value)}><option value="">Select a prepared release</option>{candidates.map(p=><option key={p.id} value={p.id}>{p.name} · version {p.version}</option>)}</select></label><label>Format<select value={format} onChange={e=>{setFormat(e.target.value as 'physical'|'digital');setStock(false);}}><option value="physical">One physical unit</option><option value="digital">One STL download</option></select></label></div>
 <label>Exact public title<input required minLength={5} maxLength={140} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Exact public description<textarea required minLength={20} maxLength={10000} rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><p>Price: {project?.release?`USD ${((format==='physical'?project.release.physicalPriceCents:project.release.digitalPriceCents)/100).toFixed(2)} from approved release`:'Select a release'}. License text is appended and shown in the preview. Quantity: exactly one. Auto-renew at expiration is disabled.</p>
 <label>Existing Etsy taxonomy ID<input required type="number" min={1} value={taxonomy} onChange={e=>setTaxonomy(e.target.value)}/></label>{format==='physical'&&<div className={styles.grid}><label>Existing shipping profile ID<input required type="number" min={1} value={shipping} onChange={e=>setShipping(e.target.value)}/></label><label>Existing processing/readiness profile ID<input required type="number" min={1} value={processing} onChange={e=>setProcessing(e.target.value)}/></label><label>Existing return policy ID<input required type="number" min={1} value={returns} onChange={e=>setReturns(e.target.value)}/></label></div>}
 <label>Original accurate listing photo (JPEG/PNG, under 8 MB)<input required type="file" accept="image/jpeg,image/png" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><p>Digital upload uses the exact existing tested STL automatically, under 20 MB. No remote photo download or generated placeholder is substituted.</p>
 <label className={styles.check}><input required type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>I own this original design and photo and reviewed Etsy Creativity Standards.</label><label className={styles.check}><input required type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/>{format==='physical'?'I reserved one separate physical Etsy unit, unavailable to storefront buyers.':'I approve one digital sale before a manual replenishment review.'}</label><label className={styles.check}><input required type="checkbox" checked={policies} onChange={e=>setPolicies(e.target.checked)}/>I reviewed the accurate product description, license, taxonomy, shipping/processing/return policies and seller tax settings.</label><button disabled={busy||!project||!photo||!rights||!stock||!policies}>Prepare preview without external writes</button></form>
 <h3>Publication previews and outcomes</h3>{!data?.publications.length&&<p>No packages prepared.</p>}{data?.publications.map(p=><details key={p.id} className={styles.approval}><summary>{p.package.title} · {p.package.format} · {p.status}</summary><p>{p.step}</p><p>Project version {p.version} · revision {p.package.revisionId} · shop {p.shopId} · SHA256 {p.hash}</p><pre>{JSON.stringify(p.package,null,2)}</pre>{p.listingId&&<p><a href={`https://www.etsy.com/listing/${p.listingId}`} target="_blank" rel="noreferrer">Review Etsy listing {p.listingId}</a></p>}{p.status==='preview'&&<><p><a href={p.package.feePolicyUrl} target="_blank" rel="noreferrer">Review Etsy fee policy</a>. {p.package.feeLimitations}</p><label className={styles.check}><input type="checkbox" checked={approval===p.id} onChange={e=>setApproval(e.target.checked?p.id:'')}/>I approve this exact preview, public publication now and Etsy listing fees/taxes and future applicable sales fees. The single Etsy unit is separately allocated. I understand platform billing is separate from the AI cap.</label><button type="button" disabled={busy||!data.writesEnabled||approval!==p.id} onClick={()=>void publish(p)}>Approve fee spending & publish this exact listing</button></>}</details>)}
 </article>;
}
