'use client';
import {useCallback,useEffect,useState} from 'react';
import type {ProductProject} from '@/lib/ai-center/projects';
import type {Job} from '@/lib/ai-center/types';
import type {MarketplaceStore} from '@/lib/marketplace/store';
import type {connectionConfiguration,observeMarket,readOwnSales} from '@/lib/marketplace/etsy';
import styles from './AiBusinessCenter.module.css';
import {evidenceFromObservation} from '@/lib/marketplace/evidence';

type Market=Awaited<ReturnType<typeof observeMarket>>;
type Sales=Awaited<ReturnType<typeof readOwnSales>>;
type Failure={kind:'research-failure';query:string;observedAt:string;message:string};
type Snapshot={configuration:ReturnType<typeof connectionConfiguration>;connection:ReturnType<MarketplaceStore['status']>;reports:(Market|Sales|Failure)[];eligibleProjectIds:string[]};
const price=(cents:number,currency:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(cents/100);
export function MarketplaceConnections({projects=[],onProjectChanged}:{projects?:ProductProject[];jobs?:Job[];onProjectChanged?:()=>Promise<void>}){
 const [data,setData]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[keywords,setKeywords]=useState('small PLA desk organizer'),[days,setDays]=useState(30),[listing,setListing]=useState('');
 const [selectedProject,setSelectedProject]=useState(''),[evidence,setEvidence]=useState<{label:string;url:string;signal:string}|null>(null),[reviewed,setReviewed]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/owner/marketplace',{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.message||'Marketplace unavailable.');setData(v);}catch(e){setError(e instanceof Error?e.message:'Marketplace unavailable.');}},[]);
 useEffect(()=>{void load();},[load]);
 async function command(value:unknown){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/owner/marketplace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}),v=await r.json();if(!r.ok)throw Error(v.message||'Marketplace action failed.');if(v.url){const u=new URL(v.url);if(u.origin!=='https://www.etsy.com'||u.pathname!=='/oauth/connect')throw Error('Invalid authorization URL.');window.location.assign(u.toString());return;}if(v.listing)setListing(JSON.stringify(v.listing,null,2));setMessage(v.message||'Read completed. Sources and limits are shown below.');await load();}catch(e){setError(e instanceof Error?e.message:'Marketplace action failed.');}finally{setBusy(false);}}
 const ready=projects.filter(p=>p.stage==='release'&&data?.eligibleProjectIds.includes(p.id));
 async function attach(){const project=projects.find(p=>p.id===selectedProject);if(!project||!evidence||!reviewed)return;setBusy(true);setError('');try{const r=await fetch('/api/owner/business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'project',id:project.id,version:project.version,change:{action:'evidence',...evidence}})}),v=await r.json();if(!r.ok)throw Error(v.message||'Project changed; refresh before attaching evidence.');setMessage('Reviewed observation attached to project research. Delegate the next research draft from the project workspace.');setEvidence(null);setReviewed(false);await onProjectChanged?.();}catch(e){setError(e instanceof Error?e.message:'Could not attach evidence.');}finally{setBusy(false);}}
 return <article className={styles.card}><h2>Etsy connection & research</h2><p>Official API observations and your own shop transactions. Listing text and popularity signals require human review. Competitor sales and bestseller rankings are unavailable.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}<p role="status" aria-live="polite">{message}</p>
 {!data?<p>Loading private connection status…</p>:<>
  <p>Expected shop: <strong>{data.configuration.expectedShop}</strong> · {data.connection.connected?`Authorized: ${data.connection.shopName}`:'Not authorized'} · {data.configuration.mode}</p>
  {!data.configuration.enabled&&<p><strong>Setup required:</strong> Etsy integration is disabled. Register and obtain approval for an Etsy developer app, configure the server secrets and callback, then explicitly enable the adapter.</p>}
  {!!data.configuration.missing.length&&<p>Missing server configuration: {data.configuration.missing.join(', ')}.</p>}
  {data.connection.expiresAt&&<p>Access token expires {new Date(data.connection.expiresAt).toLocaleString()}. Expired tokens refresh only during an owner-requested shop read. Scope: {data.connection.scopes.join(', ')}.</p>}
  <button type="button" disabled={busy||!data.configuration.enabled||!!data.configuration.missing.length} onClick={()=>void command({action:'connect'})}>{data.connection.connected?'Reauthorize Etsy read access':'Authorize Etsy read access'}</button>{' '}
  <button type="button" disabled={busy||!data.connection.connected} onClick={()=>void command({action:'disconnect'})}>Remove local authorization</button>
  <p>Browser sign-in, including Sign in with Apple, does not authorize this application. The research flow asks Etsy for read-only access. Listing publication needs a separate write grant and exact owner approval in the publication panel. No messaging, payment, refund or paid-search executor is connected.</p>
  <div className={styles.grid}><form onSubmit={e=>{e.preventDefault();void command({action:'research',keywords});}}><h3>Observe a product category</h3><label>Research phrase<input required maxLength={120} value={keywords} onChange={e=>setKeywords(e.target.value)}/></label><button disabled={busy||!data.configuration.enabled||!!data.configuration.missing.length}>Read first 25 Etsy search results</button><p>App access may restrict marketplace search. Sources and timestamps are preserved. Results are not sent to AI automatically.</p></form>
  <form onSubmit={e=>{e.preventDefault();void command({action:'sales',options:{days,maxPages:3}});}}><h3>Own-shop sales observations</h3><label>Window (days)<input required type="number" min={1} max={365} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><button disabled={busy||!data.configuration.enabled||!data.connection.connected}>Read up to 300 paid receipts</button><p>Units sold by listing within your authorized shop. This is not marketplace-wide demand or net profit.</p></form></div>
  <h3>Prepared manual listing packages</h3><p>Exports require a current passing physical test and an approved listing draft for that exact project version. Publication remains a manual owner action. Assign Etsy stock separately from your storefront.</p>
  {ready.length?ready.map(p=><p key={p.id}>{p.name}{' '}<button disabled={busy} type="button" onClick={()=>void command({action:'export',projectId:p.id,version:p.version,format:'physical'})}>Export physical listing</button>{' '}<button disabled={busy} type="button" onClick={()=>void command({action:'export',projectId:p.id,version:p.version,format:'digital'})}>Export STL listing</button></p>):<p>No approved, tested listing package is ready.</p>}
  {listing&&<label>Manual listing export<textarea readOnly rows={14} value={listing}/></label>}
  <h3>Saved observations · latest 20</h3>{!data.reports.length&&<p>No API observations recorded. No example results are shown as real data.</p>}
  {evidence&&<form onSubmit={e=>{e.preventDefault();void attach();}}><h3>Review observation before adding to a project</h3><label>Project<select required value={selectedProject} onChange={e=>setSelectedProject(e.target.value)}><option value="">Select a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · version {p.version}</option>)}</select></label><p>{evidence.label} · <a href={evidence.url} target="_blank" rel="noreferrer">Official source</a></p><label>Factual research summary<textarea required rows={8} maxLength={2000} value={evidence.signal} onChange={e=>{setEvidence({...evidence,signal:e.target.value});setReviewed(false);}}/></label><label className={styles.check}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the source/date and proxy limitations. Add this bounded summary to project research.</label><button disabled={busy||!reviewed||!selectedProject||!evidence.signal.trim()}>Attach reviewed evidence</button>{' '}<button type="button" onClick={()=>{setEvidence(null);setReviewed(false);}}>Cancel</button></form>}
  {data.reports.map((report,index)=><details key={`${report.observedAt}-${index}`} className={styles.approval}><summary>{report.kind==='sales'?`${report.shopName} own-shop sales`:report.kind==='market'?report.query:`Research unavailable: ${report.query}`} · {new Date(report.observedAt).toLocaleString()}</summary>
   {report.kind==='research-failure'?<p>{report.message}</p>:report.kind==='market'?<><p>{report.limitations}</p><p>Reported keyword matches: {report.reportedMatches}. Observed: {report.items.length}.</p><p><a href={report.source} target="_blank" rel="noreferrer">Official API source</a></p><ul>{report.items.map(item=><li key={item.id}><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a> · {price(item.priceCents,item.currency)} · favorites: {item.favorites??'unavailable'}</li>)}</ul></>:<><p>{report.limitations}</p><p>{report.windowDays} days · {report.receiptCount} receipts observed of {report.reportedReceiptCount} reported · {report.truncated?'Truncated sample':'Returned window complete'} · {report.receiptsWithRefunds} receipts with refunds.</p><ul>{report.rankings.map(item=><li key={`${item.listingId}-${item.currency}`}><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a> · {item.units} recorded units · item gross {price(item.itemGrossCents,item.currency)}</li>)}</ul><p>Source window: {report.from} to {report.to}.</p><ul>{report.sources.map(source=><li key={source}><a href={source} target="_blank" rel="noreferrer">Official receipt API source</a></li>)}</ul></>}
   {report.kind!=='research-failure'&&<button type="button" disabled={busy||!projects.length} onClick={()=>{setEvidence(evidenceFromObservation(report));setReviewed(false);}}>Review & attach to a project</button>}
  </details>)}
 </>}
 </article>;
}
