"use client";
import { useMemo } from "react";
import type { BambuFilamentCatalogItem, PricingSettings, QuoteCostInput } from "@/lib/pricing-types";
import type { ResolvedMaterialCost } from "@/lib/material-cost-resolver";
import { contributionMetrics, materialCostCents, suggestedRevenueCents } from "@/lib/pricing-math";

function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);}
function dollars(cents:number){return (cents/100).toFixed(2);}
function number(value:string){const n=Number(value);return Number.isFinite(n)&&n>=0?n:0;}
function sourceLabel(source:ResolvedMaterialCost["source"]){return source==="actual-average"?"Actual purchase average":source==="bambu-msrp"?"Bambu MSRP":source==="manual-fallback"?"Manual fallback":"Unpriced";}
export type OwnerQuoteCostPanelProps={settings:PricingSettings;catalog:BambuFilamentCatalogItem[];materialCosts:Record<string,ResolvedMaterialCost>;value:QuoteCostInput;customerTotalCents:number;shippingInternalCostCents:number;disabled:boolean;onChange:(next:QuoteCostInput)=>void;onUseSuggestedPrice:(suggestedTotalCents:number)=>void};
export function OwnerQuoteCostPanel({settings,catalog,materialCosts,value,customerTotalCents,shippingInternalCostCents,disabled,onChange,onUseSuggestedPrice}:OwnerQuoteCostPanelProps){
  function patch(patch:Partial<QuoteCostInput>){onChange({...value,...patch});}
  function changeLine(index:number,patch:Partial<QuoteCostInput["materialLines"][number]>){patchLines(value.materialLines.map((line,i)=>i===index?{...line,...patch}:line));}
  function patchLines(materialLines:QuoteCostInput["materialLines"]){patch({materialLines});}
  const calc=useMemo(()=>{
    const materials=value.materialLines.map(line=>{const item=catalog.find(c=>c.id===line.catalogItemId);const cost=materialCosts[line.catalogItemId];const extended=materialCostCents(line.grams,cost?.costPerGramMicros||0);return{line,item,cost,extended};});
    const materialTotal=materials.reduce((sum,row)=>sum+row.extended,0);
    const nonPayment=materialTotal+Math.round(value.machineHours*settings.defaultMachineHourlyCostCents)+Math.round(value.designHours*settings.defaultDesignHourlyCostCents)+Math.round(value.laborHours*settings.defaultLaborHourlyCostCents)+Math.round(value.postProcessingHours*settings.defaultPostProcessingHourlyCostCents)+value.packagingCostCents+value.localDeliveryInternalCostCents+value.miscellaneousCostCents+shippingInternalCostCents;
    const metrics=contributionMetrics(customerTotalCents,nonPayment,settings);let suggested=0;let suggestionError="";try{suggested=suggestedRevenueCents(nonPayment,settings);}catch(error){suggestionError=error instanceof Error?error.message:"Pricing target is invalid.";}
    const unpriced=materials.some(row=>row.line.grams>0&&(!row.cost||row.cost.source==="unpriced"));
    return{materials,materialTotal,nonPayment,metrics,suggested,suggestionError,unpriced};
  },[value,catalog,materialCosts,settings,customerTotalCents,shippingInternalCostCents]);
  const grouped=Array.from(new Set(catalog.filter(x=>x.active).map(x=>x.materialClass)));
  return <section className="quote-cost-panel"><div className="quote-cost-heading"><div><span>COST &amp; MARGIN — OWNER ONLY</span><strong>Estimate the real contribution before sending.</strong></div><em>{settings.targetContributionMarginBasisPoints?`Target ${(settings.targetContributionMarginBasisPoints/100).toFixed(1)}%`:"Target margin not set"}</em></div>
    <div className="quote-cost-materials"><div className="quote-cost-section-title"><strong>Bambu material</strong><button type="button" className="text-button" disabled={disabled||value.materialLines.length>=20} onClick={()=>patchLines([...value.materialLines,{id:crypto.randomUUID(),catalogItemId:catalog[0]?.id||"",grams:0}])}>+ Add material</button></div>{value.materialLines.length===0?<div className="quote-cost-empty">Add the Bambu filament and estimated grams for this print.</div>:value.materialLines.map((line,index)=>{const row=calc.materials[index];return <div className="quote-cost-material-row" key={line.id}><label><span>Filament</span><select disabled={disabled} value={line.catalogItemId} onChange={e=>changeLine(index,{catalogItemId:e.target.value})}><option value="">Choose Bambu filament</option>{grouped.map(group=><optgroup label={group} key={group}>{catalog.filter(item=>item.active&&item.materialClass===group).map(item=><option value={item.id} key={item.id}>{item.displayName}</option>)}</optgroup>)}</select></label><label><span>Grams</span><input type="number" min="0" step="1" disabled={disabled} value={line.grams||""} onChange={e=>changeLine(index,{grams:number(e.target.value)})}/></label><div className="quote-cost-material-meta"><b>{row?.cost?sourceLabel(row.cost.source):"Unpriced"}</b><span>{row?.cost?.costPerGramMicros?`${money(row.cost.costPerGramMicros/1_000_000*1000)} / kg`:"No cost basis"}</span><strong>{money(row?.extended||0)}</strong></div><button type="button" className="text-button danger-text" disabled={disabled} onClick={()=>patchLines(value.materialLines.filter((_,i)=>i!==index))}>Remove</button></div>})}</div>
    <div className="quote-cost-input-grid"><label><span>Machine hours</span><input type="number" min="0" step="0.1" disabled={disabled} value={value.machineHours||""} onChange={e=>patch({machineHours:number(e.target.value)})}/></label><label><span>Design hours</span><input type="number" min="0" step="0.1" disabled={disabled} value={value.designHours||""} onChange={e=>patch({designHours:number(e.target.value)})}/></label><label><span>Assembly / labor hours</span><input type="number" min="0" step="0.1" disabled={disabled} value={value.laborHours||""} onChange={e=>patch({laborHours:number(e.target.value)})}/></label><label><span>Post-processing hours</span><input type="number" min="0" step="0.1" disabled={disabled} value={value.postProcessingHours||""} onChange={e=>patch({postProcessingHours:number(e.target.value)})}/></label><label><span>Packaging ($)</span><input inputMode="decimal" disabled={disabled} value={dollars(value.packagingCostCents)} onChange={e=>patch({packagingCostCents:Math.round(number(e.target.value)*100)})}/></label><label><span>Internal delivery cost ($)</span><input inputMode="decimal" disabled={disabled} value={dollars(value.localDeliveryInternalCostCents)} onChange={e=>patch({localDeliveryInternalCostCents:Math.round(number(e.target.value)*100)})}/></label><label><span>Miscellaneous cost ($)</span><input inputMode="decimal" disabled={disabled} value={dollars(value.miscellaneousCostCents)} onChange={e=>patch({miscellaneousCostCents:Math.round(number(e.target.value)*100)})}/></label></div>
    {calc.unpriced&&<div className="quote-cost-warning">One or more selected filaments have no cost basis. Margin is incomplete until an invoice, MSRP, or manual fallback is available.</div>}
    <div className="quote-cost-summary"><div><span>Material</span><strong>{money(calc.materialTotal)}</strong></div><div><span>Direct cost before payment fee</span><strong>{money(calc.nonPayment)}</strong></div><div><span>Estimated payment fee</span><strong>{money(calc.metrics.paymentFeeCents)}</strong></div><div><span>Estimated direct cost</span><strong>{money(calc.metrics.directCostCents)}</strong></div><div><span>Customer total</span><strong>{money(customerTotalCents)}</strong></div><div className={calc.metrics.contributionProfitCents<0?"is-negative":""}><span>Expected contribution profit</span><strong>{money(calc.metrics.contributionProfitCents)}</strong></div><div><span>Contribution margin</span><strong>{(calc.metrics.contributionMarginBasisPoints/100).toFixed(1)}%</strong></div><div><span>Suggested total</span><strong>{settings.targetContributionMarginBasisPoints&&!calc.suggestionError?money(calc.suggested):"Set target margin"}</strong></div></div>
    {calc.suggestionError&&<div className="quote-cost-warning">{calc.suggestionError}</div>}
    {!settings.targetContributionMarginBasisPoints&&<div className="quote-cost-note">Set a target contribution margin in Pricing &amp; Profitability to enable margin-target pricing guidance.</div>}
    {settings.targetContributionMarginBasisPoints>0&&!calc.unpriced&&!calc.suggestionError&&<button className="button button-secondary button-small" type="button" disabled={disabled} onClick={()=>onUseSuggestedPrice(calc.suggested)}>Use Suggested Price</button>}
  </section>;
}
