"use client";
import { useEffect, useState } from "react";
import type { AuditEntry } from "@/lib/audit-log";

type BackupInfo={name:string;createdAt:string;databaseBytes:number;includesPrivateFiles:boolean};
type StripeStatus={keyConfigured:boolean;webhookConfigured:boolean;mode:"test"|"live"|"unconfigured";siteOrigin:string;secureOrigin:boolean;webhookUrl:string;checkoutReady:boolean;productionReady:boolean};
type ShippingStatus={configured:boolean;mode:"test"|"production"|"unconfigured";fromAddressConfigured:boolean};
type Notice={kind:"success"|"error"|"warning";text:string}|null;
export function OwnerSecurityPanel({onNotice}:{onNotice:(n:Notice)=>void}){
  const [audit,setAudit]=useState<AuditEntry[]>([]);const [backups,setBackups]=useState<BackupInfo[]>([]);const [stripe,setStripe]=useState<StripeStatus|null>(null);const [shipping,setShipping]=useState<ShippingStatus|null>(null);const [busy,setBusy]=useState(false);
  async function load(){
    const [a,b,p,s]=await Promise.all([fetch("/api/owner/audit",{cache:"no-store"}),fetch("/api/owner/backups",{cache:"no-store"}),fetch("/api/owner/payments/status",{cache:"no-store"}),fetch("/api/owner/shipping/status",{cache:"no-store"})]);
    if(a.ok){const j=await a.json() as {entries?:AuditEntry[]};setAudit(j.entries||[]);}if(b.ok){const j=await b.json() as {backups?:BackupInfo[]};setBackups(j.backups||[]);}if(p.ok){const j=await p.json() as {stripe?:StripeStatus};setStripe(j.stripe||null);}if(s.ok){const j=await s.json() as {shipping?:ShippingStatus};setShipping(j.shipping||null);}
  }
  useEffect(()=>{void load();},[]);
  async function backup(){setBusy(true);try{const r=await fetch("/api/owner/backups",{method:"POST"});const j=await r.json() as {message?:string};if(!r.ok)throw new Error(j.message||"Could not create backup.");onNotice({kind:"success",text:"Secure backup snapshot created."});await load();}catch(e){onNotice({kind:"error",text:e instanceof Error?e.message:"Could not create backup."});}finally{setBusy(false);}}
  async function copyWebhook(){if(!stripe?.webhookUrl)return;try{await navigator.clipboard.writeText(stripe.webhookUrl);onNotice({kind:"success",text:"Stripe webhook URL copied."});}catch{onNotice({kind:"warning",text:"Could not copy automatically. Select the webhook URL manually."});}}
  return <div className="owner-security-grid">
    <section className="owner-panel owner-payment-panel"><div className="owner-panel-heading"><div><p className="eyebrow">PAYMENTS</p><h2>Stripe deposit setup</h2></div><button className="text-button" type="button" onClick={()=>void load()}>Refresh</button></div><p className="owner-panel-intro">Customers pay the 50% deposit on Stripe-hosted Checkout. Secret keys stay in server environment variables and are never returned to this dashboard.</p>
      {!stripe?<div className="queue-empty compact"><strong>Checking Stripe configuration…</strong></div>:<><div className="stripe-status-grid"><article className={stripe.keyConfigured?"is-ready":"is-missing"}><span>Server key</span><strong>{stripe.keyConfigured?"Configured":"Missing"}</strong><small>{stripe.mode==="test"?"Sandbox / test mode":stripe.mode==="live"?"Live payments":"Add STRIPE_SECRET_KEY"}</small></article><article className={stripe.webhookConfigured?"is-ready":"is-missing"}><span>Webhook signing</span><strong>{stripe.webhookConfigured?"Configured":"Missing"}</strong><small>{stripe.webhookConfigured?"Signed events can be verified":"Add STRIPE_WEBHOOK_SECRET"}</small></article><article className={stripe.secureOrigin?"is-ready":"is-warning"}><span>Public site URL</span><strong>{stripe.secureOrigin?"HTTPS ready":"Local / not HTTPS"}</strong><small>{stripe.siteOrigin}</small></article><article className={stripe.productionReady?"is-ready":"is-warning"}><span>Go-live status</span><strong>{stripe.productionReady?"Ready for live deposits":stripe.checkoutReady?"Testing available":"Setup incomplete"}</strong><small>{stripe.productionReady?"Live key + webhook + HTTPS detected":"Finish the checklist before real charges"}</small></article></div><div className="stripe-webhook-box"><div><span>Webhook endpoint</span><code>{stripe.webhookUrl}</code></div><button className="button button-secondary button-small" type="button" onClick={()=>void copyWebhook()}>Copy URL</button></div><div className="stripe-setup-note"><strong>Recommended sequence</strong><span>Start with Stripe test mode, configure the webhook, complete a test deposit, then replace the test key with a live restricted/secret key only when the site is on HTTPS.</span></div></>}
    </section>
    <section className="owner-panel owner-payment-panel"><div className="owner-panel-heading"><div><p className="eyebrow">SHIPPING</p><h2>EasyPost live carrier rates</h2></div><button className="text-button" type="button" onClick={()=>void load()}>Refresh</button></div><p className="owner-panel-intro">EasyPost supplies live USPS, UPS, and FedEx rates from the packed box size, packed weight, ship-from address, and the customer&apos;s private delivery address. Stripe collects the payment after the customer chooses a rate.</p>
      {!shipping?<div className="queue-empty compact"><strong>Checking EasyPost configuration…</strong></div>:<div className="stripe-status-grid"><article className={shipping.configured?"is-ready":"is-missing"}><span>EasyPost API</span><strong>{shipping.configured?"Configured":"Missing"}</strong><small>{shipping.mode==="test"?"Test mode":shipping.mode==="production"?"Production rates":"Add EASYPOST_API_KEY"}</small></article><article className={shipping.fromAddressConfigured?"is-ready":"is-missing"}><span>Ship-from address</span><strong>{shipping.fromAddressConfigured?"Configured":"Missing"}</strong><small>{shipping.fromAddressConfigured?"Origin available for rate calculation":"Add SHIPPING_FROM_* values"}</small></article><article className={shipping.configured&&shipping.fromAddressConfigured?"is-ready":"is-warning"}><span>Customer rate shopping</span><strong>{shipping.configured&&shipping.fromAddressConfigured?"Ready":"Setup incomplete"}</strong><small>USPS · UPS · FedEx</small></article></div>}
    </section>
    <section className="owner-panel"><div className="owner-panel-heading"><div><p className="eyebrow">BACKUPS</p><h2>Database & private files</h2></div><button className="button button-small" disabled={busy} onClick={()=>void backup()} type="button">{busy?"Creating…":"Create Backup"}</button></div><p className="owner-panel-intro">A daily snapshot is created when the owner dashboard checks backup status. Manual snapshots include the SQLite database and private customer-upload storage, and old backups are rotated automatically.</p><div className="backup-list">{backups.length===0?<div className="queue-empty compact"><strong>No backups yet.</strong></div>:backups.map(item=><article key={item.name}><div><strong>{item.name}</strong><small>{new Date(item.createdAt).toLocaleString()}</small></div><span>{(item.databaseBytes/1024/1024).toFixed(2)} MB DB {item.includesPrivateFiles?"+ private files":""}</span></article>)}</div></section>
    <section className="owner-panel"><div className="owner-panel-heading"><div><p className="eyebrow">AUDIT LOG</p><h2>Security & business actions</h2></div><button className="text-button" type="button" onClick={()=>void load()}>Refresh</button></div><p className="owner-panel-intro">Sensitive actions are timestamped with the actor and a privacy-preserving hashed IP marker. Raw IP addresses are not stored.</p><div className="audit-list">{audit.length===0?<div className="queue-empty compact"><strong>No audit events yet.</strong></div>:audit.map(item=><article key={item.id}><div><strong>{item.summary}</strong><small>{new Date(item.createdAt).toLocaleString()} • {item.actor} • {item.action}</small></div><span>{item.ipHash||"system"}</span></article>)}</div></section>
  </div>;
}
