"use client";
import { useEffect, useMemo, useState } from "react";
import type { StoredQuote } from "@/lib/quote-types";
import type { BambuFilamentCatalogItem, PricingSettings, QuoteCostInput, QuoteCostSnapshot } from "@/lib/pricing-types";
import type { ResolvedMaterialCost } from "@/lib/material-cost-resolver";
import { OwnerQuoteCostPanel } from "@/components/OwnerQuoteCostPanel";
type Notice={kind:"success"|"error"|"warning";text:string}|null;
function inputFrom(snapshot:QuoteCostSnapshot):QuoteCostInput{return{materialLines:snapshot.materialLines.map(x=>({id:x.id,catalogItemId:x.catalogItemId,grams:x.grams})),machineHours:snapshot.machineHours,designHours:snapshot.designHours,laborHours:snapshot.laborHours,postProcessingHours:snapshot.postProcessingHours,packagingCostCents:snapshot.packagingCostCents,localDeliveryInternalCostCents:snapshot.localDeliveryInternalCostCents,miscellaneousCostCents:snapshot.miscellaneousCostCents};}
function money(c:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);}
export function OwnerCostCloseout({requestId,quote,settings,catalog,materialCosts,snapshots,onChanged,onNotice}:{requestId:string;quote:StoredQuote;settings:PricingSettings;catalog:BambuFilamentCatalogItem[];materialCosts:Record<string,ResolvedMaterialCost>;snapshots:QuoteCostSnapshot[];onChanged:()=>Promise<void>;onNotice:(n:Notice)=>void}){
 const estimate=useMemo(()=>snapshots.find(x=>x.quoteId===quote.id&&x.quoteRevision===quote.revision&&x.status==="estimate")||null,[snapshots,quote.id,quote.revision]);
 const actual=useMemo(()=>snapshots.find(x=>x.quoteId===quote.id&&x.quoteRevision===quote.revision&&x.status!=="estimate")||null,[snapshots,quote.id,quote.revision]);
 const [value,setValue]=useState<QuoteCostInput|null>(actual?inputFrom(actual):estimate?inputFrom(estimate):null),[busy,setBusy]=useState("");
 useEffect(()=>setValue(actual?inputFrom(actual):estimate?inputFrom(estimate):null),[actual,estimate]);
 async function action(name:"use-estimate"|"finalize"|"reopen"){setBusy(name);try{const r=await fetch(`/api/owner/requests/${requestId}/cost-closeout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:name})});const j=await r.json() as {message?:string};if(!r.ok)throw new Error(j.message||"Could not update cost closeout.");onNotice({kind:"success",text:j.message||"Cost closeout updated."});await onChanged();}catch(e){onNotice({kind:"error",text:e instanceof Error?e.message:"Could not update cost closeout."});}finally{setBusy("");}}
 async function save(){if(!value)return;setBusy("save");try{const r=await fetch(`/api/owner/requests/${requestId}/cost-closeout`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const j=await r.json() as {message?:string};if(!r.ok)throw new Error(j.message||"Could not save actual costing.");onNotice({kind:"success",text:j.message||"Actual costing saved."});await onChanged();}catch(e){onNotice({kind:"error",text:e instanceof Error?e.message:"Could not save actual costing."});}finally{setBusy("");}}
 if(!estimate&&!actual)return <section className="owner-cost-closeout is-uncosted"><div><span>ACTUAL COST CLOSEOUT</span><strong>Not costed</strong><small>Create a Cost &amp; Margin estimate in the Quote Workspace first.</small></div></section>;
 const editable=Boolean(actual&&actual.status!=="finalized");
 return <details className="owner-cost-closeout"><summary><span><b>ACTUAL COST CLOSEOUT</b><strong>{actual?actual.status==="finalized"?`Finalized · ${money(actual.contributionProfitCents)} contribution`:`Actual draft · ${money(actual.contributionProfitCents)} contribution`:"Estimate available — actuals not started"}</strong></span><em>{actual?`${(actual.contributionMarginBasisPoints/100).toFixed(1)}% margin`:"Start closeout"}</em></summary><div className="owner-cost-closeout-body">{!actual&&estimate&&<button className="button button-secondary button-small" type="button" disabled={Boolean(busy)} onClick={()=>void action("use-estimate")}>Use Estimates as Actuals</button>}{actual&&value&&<><OwnerQuoteCostPanel settings={settings} catalog={catalog} materialCosts={materialCosts} value={value} customerTotalCents={quote.totalCents} shippingInternalCostCents={actual.shippingInternalCostCents} disabled={!editable||Boolean(busy)} onChange={setValue} onUseSuggestedPrice={()=>{}}/><div className="owner-cost-closeout-actions">{editable&&<button className="button button-secondary button-small" type="button" disabled={Boolean(busy)} onClick={()=>void save()}>Save Actual Costs</button>}{editable&&<button className="button button-small" type="button" disabled={Boolean(busy)} onClick={()=>void action("finalize")}>Finalize Costing</button>}{actual.status==="finalized"&&<button className="button button-secondary button-small" type="button" disabled={Boolean(busy)} onClick={()=>void action("reopen")}>Reopen Costing</button>}</div></>}</div></details>;
}
