'use client';
import {useState} from 'react';
import type {ProductProject} from '@/lib/ai-center/projects';
import type {Agent,Job} from '@/lib/ai-center/types';
import styles from './AiBusinessCenter.module.css';
type Props={projects:ProductProject[];jobs:Job[];busy:boolean;command:(value:unknown)=>Promise<boolean>;reload:()=>Promise<void>};
const businesses={mesh:'Mesh Harbor · prints & STLs',products:'Independent digital products'};
const roles={plan:'Leader',research:'Research',design:'Design / refinement',listing:'Listing',idea:'Ideas',review:'Operations',outreach:'Outreach drafts'};
const usd=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
export function ProductProjects({projects,jobs,busy,command,reload}:Props){
 const [business,setBusiness]=useState<Agent>('mesh'),[selected,setSelected]=useState(''),[view,setView]=useState<'projects'|'products'|'stls'|'cart'>('projects');
 const [cart,setCart]=useState<{id:string;digital:boolean;revision:string}[]>([]);
 const [uploadMessage,setUploadMessage]=useState(''),[uploadBusy,setUploadBusy]=useState(false);
 const p=projects.find(x=>x.id===selected&&x.business===business);
 const releaseProjects=projects.filter(x=>x.business===business&&x.release);
 const validCart=cart.filter(c=>projects.some(x=>x.id===c.id&&x.release?.revisionId===c.revision));
 return <section className={styles.card}>
  <h2>Your business workspaces</h2><div className={styles.grid}>{(Object.keys(businesses) as Agent[]).map(id=><button key={id} aria-pressed={business===id} onClick={()=>{setBusiness(id);setSelected('');setView('projects');}}>{businesses[id]} · {projects.filter(p=>p.business===id).length} projects</button>)}</div>
  <nav aria-label="Business sections">{(['projects','products','stls','cart'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='projects'?'Project board':v==='products'?'Products preview':v==='stls'?'STLs preview':`Cart preview (${validCart.length})`}</button>)}</nav>
  <p>Private previews. No public listing, payment, stock reservation or customer downloads are enabled.</p>
  {view==='projects'?<>
   <h3>Leader → research → design/refinement → listing</h3><p>The coordinator assigns a bounded draft task for the current project stage. Review the leader plan before delegation. Paid calls still require approval. Role tasks share their business’s monthly budget.</p>
   <div className={styles.grid}>{Object.entries(roles).slice(0,4).map(([kind,name])=>{const matching=jobs.filter(j=>j.agent===business&&j.kind===kind);return <div key={kind} className={styles.approval}><strong>{name}</strong><p>{matching.filter(j=>j.status==='running').length} running · {matching.filter(j=>j.status==='queued').length} queued · {matching.filter(j=>['review','spend-review'].includes(j.status)).length} awaiting owner</p></div>;})}</div>
   <h3>Your next actions</h3>{projects.filter(x=>x.business===business).length?<ul>{projects.filter(x=>x.business===business).map(x=><li key={x.id}><button onClick={()=>setSelected(x.id)}>{x.name}</button> · {x.stage==='test'?'Slice and physically test the latest STL':x.stage==='refine'?'Review failure notes and make a new revision':x.stage==='release'?'Review listing drafts, photos, shipping and release readiness':x.stage==='research'?'Add sourced market observations; review leader plan':'Develop the design or prepare a tested release package'}</li>)}</ul>:<p>Add your first idea below.</p>}
   <details><summary>Add an idea to the workflow</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await command({action:'createProject',project:{business,name:f.get('name'),brief:f.get('brief')}}))form.reset();}}>
    <label>Project name<input name="name" required maxLength={100}/></label><label>Idea / customer problem<textarea name="brief" required maxLength={2000} rows={3}/></label><button disabled={busy}>Add project</button>
   </form></details>
   {p&&<article className={styles.approval}><h3>{p.name} · {p.stage}</h3><p>{p.brief}</p><button disabled={busy||p.stage==='test'} onClick={()=>void command({action:'delegate',id:p.id,version:p.version})}>Leader: queue next role task</button>
    <details><summary>Research evidence · {p.evidence.length}</summary><p>Record public demand signals with sources. Review counts and search placement are proxies, not verified item sales. No automatic browsing is connected.</p><ul>{p.evidence.map((e,i)=><li key={i}><a href={e.url} target="_blank" rel="noopener noreferrer">{e.label}</a> · {e.signal} · {new Date(e.at).toLocaleDateString()}</li>)}</ul><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command({action:'project',id:p.id,version:p.version,change:{action:'evidence',label:f.get('label'),url:f.get('url'),signal:f.get('signal')}});}}><label>Source label<input name="label" required maxLength={120}/></label><label>HTTPS source URL<input name="url" type="url" required maxLength={1000}/></label><label>What you observed / limitations<textarea name="signal" required maxLength={2000}/></label><button disabled={busy}>Add observation</button></form></details>
    <details><summary>Design files & revisions · {p.revisions.length}</summary><p>Immutable files, hashes and physical tests stay together. New revisions invalidate release preparation. Up to 20 revisions of 1 MB each.</p>
     {p.revisions.map((r,i)=><div key={r.id} className={styles.approval}><a href={`/api/owner/business/assets?id=${r.id}`}>Download revision {i+1} · {r.filename}</a><p>{r.notes}</p><p>{r.inspection.sizeMm.join(' × ')} mm · {r.inspection.triangles} triangles · structural checks passed</p><details><summary>File identity and test history</summary><p>SHA-256: {r.sha256}</p><p>{r.inspection.limitations}</p>{r.tests.map((t,n)=><p key={n}>{t.passed?'PASS':'FAIL'} · {t.notes} · {t.printer} / {t.material} · {t.minutes} min / {t.grams} g · {new Date(t.at).toLocaleString()}</p>)}</details></div>)}
     <form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),file=f.get('file') as File;if(!file||file.size>1_000_000){setUploadMessage('Choose an STL up to 1 MB.');return;}setUploadBusy(true);try{const q=new URLSearchParams({id:p.id,version:String(p.version),filename:file.name,notes:String(f.get('notes'))});const res=await fetch('/api/owner/business/assets?'+q,{method:'POST',body:file,headers:{'Content-Type':'application/octet-stream'}});const v=await res.json();setUploadMessage(v.message);if(res.ok){form.reset();await reload();}}catch{setUploadMessage('Upload failed. Refresh before retrying.');}finally{setUploadBusy(false);}}}><label>Upload original/refined STL<input type="file" name="file" accept=".stl" required/></label><label>Changes / refinement notes<textarea name="notes" required maxLength={2000}/></label><button disabled={busy||uploadBusy}>Save new revision</button><p role="status">{uploadMessage}</p></form>
     <details><summary>Generate an original tray prototype (free)</summary><p>A simple parametric tray, not a validated bestseller. Dimensions assume mm; review in your slicer and test physically.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command({action:'tray',id:p.id,version:p.version,dimensions:Object.fromEntries(['width','length','height','wall','base'].map(k=>[k,Number(f.get(k))])),notes:String(f.get('notes'))});}}>{[['width',60],['length',40],['height',12],['wall',2],['base',2]].map(([name,value])=><label key={name}>{name} (mm)<input name={String(name)} type="number" step="0.1" min="1.2" max="150" defaultValue={value} required/></label>)}<label>Revision notes<input name="notes" defaultValue="Original tray prototype; physical test required." required maxLength={2000}/></label><button disabled={busy}>Generate STL revision</button></form></details>
    </details>
    {p.revisions.length>0&&<details><summary>Record physical test of the latest revision</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command({action:'project',id:p.id,version:p.version,change:{action:'test',revisionId:p.revisions.at(-1)!.id,passed:f.get('passed')==='pass',notes:f.get('notes'),printer:f.get('printer'),material:f.get('material'),minutes:Number(f.get('minutes')),grams:Number(f.get('grams'))}});}}><label>Physical result<select name="passed"><option value="fail">Needs refinement</option><option value="pass">I printed and tested this exact revision successfully</option></select></label><label>Test findings / failures / fit measurements<textarea name="notes" required maxLength={2000}/></label><label>Printer<input name="printer" defaultValue="Bambu Lab X2D (owner supplied)" required maxLength={100}/></label><label>Material<input name="material" defaultValue="Bambu PLA Matte" required maxLength={100}/></label><label>Print minutes<input name="minutes" type="number" min="1" max="10000" required/></label><label>Material grams<input name="grams" type="number" min="0.1" max="10000" step="0.1" required/></label><button disabled={busy}>Record this revision’s test</button></form></details>}
    <details><summary>Prepare release package for review</summary><p>Requires a passing physical test of the latest revision. Pricing and stock are owner estimates; no public release occurs.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command({action:'project',id:p.id,version:p.version,change:{action:'prepare',description:f.get('description'),physicalPriceCents:Math.round(Number(f.get('physical'))*100),digitalPriceCents:Math.round(Number(f.get('digital'))*100),costCents:Math.round(Number(f.get('cost'))*100),stock:Number(f.get('stock')),license:f.get('license'),original:f.get('original')==='on'}});}}><label>Accurate product description<textarea name="description" required maxLength={2000}/></label>{[['physical','Physical price'],['digital','STL price'],['cost','Estimated direct cost incl. labor, packaging & fees']].map(([name,label])=><label key={name}>{label} (USD)<input name={name} type="number" min="0" max="10000" step="0.01" required/></label>)}<label>Finished physical inventory<input name="stock" type="number" min="0" max="10000" required/></label><label>STL license and instructions<textarea name="license" required maxLength={2000}/></label><label className={styles.check}><input type="checkbox" name="original" required/>I confirm this is our original design and we have the rights to sell it.</label><button disabled={busy}>Prepare private catalog preview</button></form></details>
    <h3>Project agent interactions</h3>{jobs.filter(j=>j.projectId===p.id).map(j=><details key={j.id}><summary>{roles[j.kind]} · {j.status}</summary><pre>{j.brief}</pre>{j.output&&<pre>{j.output}</pre>}<p>Review pending jobs in the approvals inbox below.</p></details>)}
   </article>}
  </>:view==='cart'?<><h3>Cart preview</h3><p>Preview only. No checkout or inventory reservation. Changed revisions automatically disappear from this cart.</p>{validCart.map((c,i)=>{const x=projects.find(p=>p.id===c.id)!;return <p key={i}>{x.name} · {c.digital?'STL file':'Physical print'} · {usd(c.digital?x.release!.digitalPriceCents:x.release!.physicalPriceCents)} <button onClick={()=>setCart(cart.filter(entry=>entry!==c))}>Remove</button></p>;})}<strong>Preview total: {usd(validCart.reduce((sum,c)=>{const x=projects.find(p=>p.id===c.id)!;return sum+(c.digital?x.release!.digitalPriceCents:x.release!.physicalPriceCents);},0))}</strong></>:<><h3>{view==='stls'?'STL files':'Physical products'} · private preview</h3>{releaseProjects.length?releaseProjects.map(x=><article key={x.id} className={styles.approval}><h3>{x.name}</h3><p>{x.release!.description}</p><p>{usd(view==='stls'?x.release!.digitalPriceCents:x.release!.physicalPriceCents)} · {view==='stls'?'Digital file, no physical item':`${x.release!.stock} owner-reported finished units`}</p>{view==='stls'&&<p>{x.release!.license}</p>}<button disabled={view==='products'&&x.release!.stock<1} onClick={()=>setCart([...cart,{id:x.id,digital:view==='stls',revision:x.release!.revisionId}])}>Add to preview cart</button></article>):<p>No tested release packages prepared yet.</p>}</>}
 </section>;
}
