/* eslint-disable @next/next/no-img-element -- Owner-hosted photos use browser loading; no server-side URL fetch. */
'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
type Product={id:string;name:string;description:string;license:string;physicalPriceCents:number;digitalPriceCents:number;stock:number;photoUrl:string};
type Item={id:string;digital:boolean;quantity:number};
type Order={id:string;status:string;items:(Item&{name:string;priceCents:number})[];totalCents:number;fulfillment:string};
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const key='meshharbor-cart';
function savedCart():Item[]{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v.filter(i=>typeof i.id==='string'&&typeof i.digital==='boolean'&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=20).slice(0,20):[];}catch{return [];}}
export function Storefront({view}:{view:'products'|'stls'|'cart'}){
 const [products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Item[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[order,setOrder]=useState<Order|null>(null),[enabled,setEnabled]=useState(false);
 useEffect(()=>{void fetch('/api/store/catalog',{cache:'no-store'}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.message);setProducts(v.products);setEnabled(v.checkoutEnabled);setCart(savedCart());}).catch(()=>setMessage('The shop is currently unavailable.'));},[]);
 const checkOrder=useCallback(async()=>{const id=new URLSearchParams(window.location.search).get('order');if(!id)return;const token=localStorage.getItem('meshharbor-order-'+id);if(!token){setMessage('Order access is stored on the browser that began Checkout. Contact Mesh Harbor for access recovery.');return;}const r=await fetch('/api/store/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,token})});const v=await r.json();if(r.ok){setOrder(v);if(['paid','shipped'].includes(v.status)){setCart([]);localStorage.removeItem(key);}}else setMessage(v.message);},[]);
 useEffect(()=>{if(view==='cart'){const timer=setInterval(()=>void checkOrder(),5000);return ()=>clearInterval(timer);}},[view,checkOrder]);
 function save(items:Item[]){setCart(items);localStorage.setItem(key,JSON.stringify(items));}
 function add(p:Product,digital:boolean){const existing=cart.find(i=>i.id===p.id&&i.digital===digital);save(existing?cart.map(i=>i===existing?{...i,quantity:digital?1:Math.min(20,i.quantity+1)}:i):[...cart,{id:p.id,digital,quantity:1}]);setMessage(p.name+' added to your cart.');}
 async function checkout(){setBusy(true);try{const r=await fetch('/api/store/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cart)});const v=await r.json();if(!r.ok)throw Error(v.message);localStorage.setItem('meshharbor-order-'+v.orderId,v.token);window.location.assign(v.url);}catch(e){setMessage(e instanceof Error?e.message:'Checkout unavailable.');}finally{setBusy(false);}}
 async function download(id:string){if(!order)return;const token=localStorage.getItem('meshharbor-order-'+order.id);const r=await fetch('/api/store/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,token,productId:id})});if(!r.ok){setMessage('Download unavailable.');return;}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(r.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1])||'mesh-harbor.stl';a.click();URL.revokeObjectURL(url);}
 return <main style={{maxWidth:1100,margin:'auto',padding:'2rem 1rem'}}><nav style={{display:'flex',gap:20,flexWrap:'wrap'}}><Link href="/products">Physical prints</Link><Link href="/stls">STL downloads</Link><Link href="/cart">Cart ({cart.reduce((n,i)=>n+i.quantity,0)})</Link><Link href="/orders">Your orders & downloads</Link><Link href="/profile">Customer account</Link></nav><h1>{view==='cart'?'Your cart':view==='stls'?'Original STL downloads':'Mesh Harbor prints'}</h1><p role="status">{message}</p>{view==='cart'?<>
 {cart.length?cart.map(i=>{const p=products.find(p=>p.id===i.id);return <article key={i.id+String(i.digital)} style={{border:'1px solid #ddd',padding:16,marginBottom:12}}><h2>{p?.name||'Unavailable product'} · {i.digital?'Digital STL':'Physical print'}</h2><p>{p?money((i.digital?p.digitalPriceCents:p.physicalPriceCents)*i.quantity):'Remove this item before Checkout.'}</p>{!i.digital&&<label>Quantity <input type="number" min={1} max={Math.min(20,p?.stock||1)} value={i.quantity} onChange={e=>save(cart.map(x=>x===i?{...x,quantity:Math.max(1,Math.min(20,Number(e.target.value)||1))}:x))}/></label>} <button onClick={()=>save(cart.filter(x=>x!==i))}>Remove</button></article>;}):<p>Your cart is empty.</p>}
 <p>Item subtotal: {money(cart.reduce((n,i)=>{const p=products.find(p=>p.id===i.id);return n+(p?(i.digital?p.digitalPriceCents:p.physicalPriceCents)*i.quantity:0);},0))}. Shipping and applicable taxes appear in Checkout. A verified customer account is required.</p><button disabled={busy||!enabled||!cart.length||cart.some(i=>!products.some(p=>p.id===i.id))} onClick={()=>void checkout()}>Continue to secure Checkout</button>
 <button onClick={()=>void checkOrder()}>Check payment / downloads</button><details><summary>Recover access using a token from Mesh Harbor</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=String(f.get('id')),token=String(f.get('token'));localStorage.setItem('meshharbor-order-'+id,token);window.history.replaceState(null,'','/cart?order='+encodeURIComponent(id));void checkOrder();}}><label>Order ID<input name="id" required/></label><label>Private access token<input name="token" type="password" required/></label><button>Recover order access</button></form></details>{order&&<section><h2>Order {order.id}</h2><p>{order.status} · recorded total {money(order.totalCents)}</p><p>{order.fulfillment}</p>{order.items.map(i=><p key={i.id+String(i.digital)}>{i.name} × {i.quantity} {i.digital&&['paid','shipped'].includes(order.status)&&<button onClick={()=>void download(i.id)}>Download purchased STL</button>}</p>)}</section>}
 </>:<><p>{view==='stls'?'Digital files for your own printer. No physical item is shipped. Review each license and print instructions.':'Finished physical prints. Availability reflects stock allocated to this website.'}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,260px),1fr))',gap:24}}>{products.map(p=><article key={p.id} style={{border:'1px solid #ddd',borderRadius:16,padding:20}}>{/* Owner supplied product photos; avoid server-side image fetching. */}<img src={p.photoUrl} alt={p.name} style={{width:'100%',height:200,objectFit:'contain'}}/><h2>{p.name}</h2><p style={{whiteSpace:'pre-wrap'}}>{p.description}</p><strong>{money(view==='stls'?p.digitalPriceCents:p.physicalPriceCents)}</strong><p>{view==='stls'?p.license:p.stock+' available'}</p><button disabled={view==='products'&&p.stock<1} onClick={()=>add(p,view==='stls')}>Add to cart</button></article>)}</div>{!products.length&&<p>New tested products are being prepared. No products are available for purchase yet.</p>}</> }</main>;
}
