import {NextRequest} from 'next/server';
import {z} from 'zod';
import {CenterStore} from '@/lib/ai-center/store';
import {MarketplaceStore} from '@/lib/marketplace/store';
import {PublicationStore,executePublication,preparePublication,publicationSchema} from '@/lib/marketplace/publication';
import {exportListing} from '@/lib/marketplace/etsy';
import {commandText,marketplaceJson,ownerGate} from '@/lib/marketplace/http';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const reference=z.object({projectId:z.uuid(),version:z.number().int().positive()}).strict();
const confirmation=z.object({id:z.uuid(),hash:z.string().regex(/^[a-f0-9]{64}$/),publish:z.literal(true),fees:z.literal(true),stock:z.literal(true)}).strict();
async function boundedForm(request:NextRequest){const type=request.headers.get('content-type')||'';if(!type.startsWith('multipart/form-data;')||!request.body)throw Error('Invalid photo upload.');const maximum=8_100_000;if(Number(request.headers.get('content-length')||0)>maximum)throw Error('Photo upload exceeds 8 MB.');const reader=request.body.getReader();let size=0;const chunks:Uint8Array[]=[];try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maximum){await reader.cancel();throw Error('Photo upload exceeds 8 MB.');}chunks.push(value);}}finally{reader.releaseLock();}return new Response(Buffer.concat(chunks),{headers:{'Content-Type':type}}).formData();}
export async function GET(request:NextRequest){const denied=await ownerGate(request);if(denied)return denied;let pub:PublicationStore|undefined;try{pub=new PublicationStore();return marketplaceJson({writesEnabled:process.env.ETSY_WRITES_ENABLED==='true',publications:pub.list()});}catch{return marketplaceJson({message:'Publication storage unavailable.'},503);}finally{pub?.close();}}
export async function POST(request:NextRequest){const denied=await ownerGate(request,true);if(denied)return denied;let pub:PublicationStore|undefined,store:MarketplaceStore|undefined,center:CenterStore|undefined;try{
 const multipart=(request.headers.get('content-type')||'').startsWith('multipart/form-data;');pub=new PublicationStore();store=new MarketplaceStore();center=new CenterStore();
 if(multipart){const form=await boundedForm(request);if([...form.keys()].some(k=>!['reference','package','photo'].includes(k))||form.getAll('photo').length!==1)throw Error('Invalid package fields.');const ref=reference.parse(JSON.parse(String(form.get('reference')))),input=publicationSchema.parse(JSON.parse(String(form.get('package')))),photo=form.get('photo');if(!(photo instanceof File)||photo.size>8_000_000)throw Error('Original photo under 8 MB required.');const project=center.snapshot().projects.find(p=>p.id===ref.projectId);if(!project||project.version!==ref.version)throw Error('Project changed; refresh first.');const revision=project.revisions.at(-1);if(!revision)throw Error('Tested revision required.');const file=center.projectAsset(revision.id);const intent=preparePublication(pub,store,project,center.projectJobs(project.id),input,Buffer.from(await photo.arrayBuffer()),photo.name,file.data);return marketplaceJson({publication:intent});}
 const approved=confirmation.parse(await commandText(request)),intent=pub.get(approved.id),project=center.snapshot().projects.find(p=>p.id===intent.projectId);if(!project)throw Error('Project unavailable.');const result=await executePublication(pub,store,intent.id,approved.hash,project,center.projectJobs(project.id),approved,fetch,()=>{const current=center!.snapshot().projects.find(p=>p.id===intent.projectId);if(!current||current.version!==intent.version)throw Error('Project changed before publication.');exportListing(current,center!.projectJobs(current.id),intent.package.format);});return marketplaceJson({publication:result});
 }catch(e){if(e instanceof z.ZodError)return marketplaceJson({message:'Invalid publication fields or required approval missing.'},400);const message=e instanceof Error?e.message:'';const safe=/^(Etsy writes|Publication (already|preview|or project|must|asset)|Project changed|Authorize |Explicit |Original |Use an original|Invalid original photo|Price changed|Prepare a release|Current revision|A listing draft|Allocate a separate|Authorization (changed|or write)|Verify a USD|Photo upload)/.test(message);return marketplaceJson({message:safe?message:'Publication unavailable. Review configuration, project approvals and reconciliation status.'},409);}finally{center?.close();store?.close();pub?.close();}}
